// Real Android Games from Google Play Store with authentic data
export const googlePlayGames = [
  {
    id: 'raid_shadow_legends',
    title: 'RAID: Shadow Legends',
    description: 'Tactical battles await in this turn-based dark fantasy RPG. Summon hundreds of Champions from 15 factions and fight against the forces of darkness.',
    genre: 'RPG',
    price: 0,
    rating: 4.6,
    reviews: 2800000,
    cover_image: 'https://play-lh.googleusercontent.com/jpZN9QMGMvMLCFSQpOczjKBJCX_kBkRPA1JBeV1dQZUbPdcjM823JUZvjAWyKIIDTzx80A=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/jpZN9QMGMvMLCFSQpOczjKBJCX_kBkRPA1JBeV1dQZUbPdcjM823JUZvjAWyKIIDTzx80A=w2560-h1440-rw',
    platforms: ['Android', 'iOS', 'PC'],
    developer: 'Plarium Global Ltd',
    isMobile: true,
    original_year: 2018,
    downloads: '50M+',
    tags: ['Turn-Based', 'Collection', 'PvP'],
    screenshots: [
      'https://play-lh.googleusercontent.com/Ak6kFJTrX01FKLMELiAJ6Tqq3KBbLi9Fgdc1xGLa9tqQjQ4R8qPw2aAJYjqC2KBCcg=w526-h296-rw',
      'https://play-lh.googleusercontent.com/3TNCeNzvZZvqNZdK8ScPMJKdGJHXiKx_7X6nKL6tGKVYfF_5K_nRWbdU5vMmQBZBEA=w526-h296-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=EHnkV2zhsN8'
  },
  {
    id: 'blood_strike',
    title: 'Blood Strike',
    description: 'Fast-paced battle royale FPS optimized for all devices. Jump into intense matches with smooth gameplay and unique characters with special abilities.',
    genre: 'Shooter',
    price: 0,
    rating: 4.3,
    reviews: 1200000,
    cover_image: 'https://play-lh.googleusercontent.com/UDPl0DW7g5chHd5VCJgkIGFj5hzLuMPZO8-VvGRBLhH7cKEwzF6xJZ5Qb0Z1Z0Z1Z0=w526-h296-rw',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920&h=1080&fit=crop',
    platforms: ['Android', 'iOS'],
    developer: 'NetEase Games',
    isMobile: true,
    original_year: 2023,
    downloads: '10M+',
    tags: ['Battle Royale', 'FPS', 'Multiplayer'],
    screenshots: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=450&fit=crop',
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=800&h=450&fit=crop'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=zTf0Qz_Xwtg'
  },
  {
    id: 'roblox_mobile',
    title: 'Roblox',
    description: 'The ultimate virtual universe. Create, share experiences, and be anything you can imagine with millions of players worldwide.',
    genre: 'Adventure',
    price: 0,
    rating: 4.4,
    reviews: 15000000,
    cover_image: 'https://play-lh.googleusercontent.com/7cIIPlWm4m7AGqVpEsIfyL-HW4cQla4ucXnfalMft1TMIYQIlf2vqgmthlZgbNAQoaQ=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/7cIIPlWm4m7AGqVpEsIfyL-HW4cQla4ucXnfalMft1TMIYQIlf2vqgmthlZgbNAQoaQ=w2560-h1440-rw',
    platforms: ['Android', 'iOS', 'PC', 'Xbox', 'PlayStation'],
    developer: 'Roblox Corporation',
    isMobile: true,
    original_year: 2006,
    downloads: '500M+',
    tags: ['Sandbox', 'Creation', 'Social'],
    screenshots: [
      'https://play-lh.googleusercontent.com/PKQNKqy_1kGbLkUWk1-f-dZPPJhUz-bJkJ1V1aDgR_qg3iGVwvLQ7aTvD4uxBiYB3Q=w526-h296-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=OtLwuKZ0IzA'
  },
  {
    id: 'cod_mobile',
    title: 'Call of Duty: Mobile',
    description: 'The iconic FPS franchise comes to mobile. Play multiplayer maps from Black Ops and Modern Warfare, plus battle royale mode.',
    genre: 'Shooter',
    price: 0,
    rating: 4.3,
    reviews: 8500000,
    cover_image: 'https://play-lh.googleusercontent.com/uPRFWFbiASqohiTMTKrD5gErGrKxq_1DgH0npRQcvUEDDLMLTECh3xXl0STPBZZseA=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/uPRFWFbiASqohiTMTKrD5gErGrKxq_1DgH0npRQcvUEDDLMLTECh3xXl0STPBZZseA=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Activision Publishing',
    isMobile: true,
    original_year: 2019,
    downloads: '500M+',
    tags: ['Tactical Shooter', 'Battle Royale', 'Multiplayer'],
    screenshots: [
      'https://play-lh.googleusercontent.com/ZlPOZ0kR_3D8qZ0Z1Z0Z1Z0Z1Z0Z1Z0Z1Z0Z1Z0Z1Z0Z1Z0=w526-h296-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=0W2ZPF_etkc'
  },
  {
    id: 'pokemon_go',
    title: 'Pokémon GO',
    description: 'Explore the world around you and catch Pokémon in augmented reality. Join Trainers worldwide in discovering Pokémon as you explore.',
    genre: 'Adventure',
    price: 0,
    rating: 3.9,
    reviews: 12000000,
    cover_image: 'https://play-lh.googleusercontent.com/39hjeqmhsub4abx84Q4CpCQgMN9ktgwDlUWm7_ZusCZYs8EIXwSuz8C9rVL7Fj4FKmRAKVwvI3Cl2IIDTzx80A=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/39hjeqmhsub4abx84Q4CpCQgMN9ktgwDlUWm7_ZusCZYs8EIXwSuz8C9rVL7Fj4FKmRAKVwvI3Cl2IIDTzx80A=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Niantic',
    isMobile: true,
    original_year: 2016,
    downloads: '500M+',
    tags: ['AR', 'Collection', 'Location-Based'],
    screenshots: [
      'https://play-lh.googleusercontent.com/p2C4QSgAf8M-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=p2C4QSgAf8M'
  },
  {
    id: 'clash_of_clans',
    title: 'Clash of Clans',
    description: 'Build your village, train troops, and battle millions of players worldwide. Join a Clan and participate in epic Clan Wars.',
    genre: 'Strategy',
    price: 0,
    rating: 4.5,
    reviews: 45000000,
    cover_image: 'https://play-lh.googleusercontent.com/sFmWfYbYp_2ea7VRMTnwd3gjIBrPGXHj_d_ab1_k1q1p2OMk4riGMF1vqxdhONOtTYOt_BVpk7a4AYcKU68LNGQ=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/sFmWfYbYp_2ea7VRMTnwd3gjIBrPGXHj_d_ab1_k1q1p2OMk4riGMF1vqxdhONOtTYOt_BVpk7a4AYcKU68LNGQ=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Supercell',
    isMobile: true,
    original_year: 2012,
    downloads: '500M+',
    tags: ['Build & Battle', 'Strategy', 'Multiplayer'],
    screenshots: [
      'https://play-lh.googleusercontent.com/vbWyGs5JcjU-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=vbWyGs5JcjU'
  },
  {
    id: 'pubg_mobile',
    title: 'PUBG MOBILE',
    description: 'Epic battle royale masterpiece. 100 players parachute onto a remote island to battle in a winner-takes-all showdown.',
    genre: 'Shooter',
    price: 0,
    rating: 4.3,
    reviews: 35000000,
    cover_image: 'https://play-lh.googleusercontent.com/zCSGnBtZk0Lmp1BAbyaZfLktDzHmC6oke67qzz3G1lBegAF2asyt5KzXOJ2PVdHDYkU=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/zCSGnBtZk0Lmp1BAbyaZfLktDzHmC6oke67qzz3G1lBegAF2asyt5KzXOJ2PVdHDYkU=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Tencent Games',
    isMobile: true,
    original_year: 2018,
    downloads: '1B+',
    tags: ['Battle Royale', 'Tactical Shooter', 'Team Play'],
    screenshots: [
      'https://play-lh.googleusercontent.com/EC0wj8kfJi6Y0Hfmve_8dLwDI7eksJQ71NU2Ccr5WUM-4MPA2XB3yhOEmbIUrzxZTfqRJjL6DbrhtH6HWOha5WI=w526-h296-rw'
    ]
  },
  {
    id: 'clash_royale',
    title: 'Clash Royale',
    description: 'Real-time multiplayer battle game featuring iconic Clash characters. Build your deck and battle in fast-paced duels.',
    genre: 'Strategy',
    price: 0,
    rating: 4.4,
    reviews: 28000000,
    cover_image: 'https://play-lh.googleusercontent.com/gnSC6s8-6Tjc4uhvDW7nfrSJxpbhllzYhgX8y374N1LYvWBStn2YhozS9XXaz1T_Pi2q=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/gnSC6s8-6Tjc4uhvDW7nfrSJxpbhllzYhgX8y374N1LYvWBStn2YhozS9XXaz1T_Pi2q=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Supercell',
    isMobile: true,
    original_year: 2016,
    downloads: '500M+',
    tags: ['Tower Defense', 'Card Battle', 'PvP'],
    screenshots: [
      'https://play-lh.googleusercontent.com/NVp3UynHfv0-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=NVp3UynHfv0'
  },
  {
    id: 'free_fire',
    title: 'Free Fire',
    description: 'Ultimate survival shooter game. Each 10-minute game places you on a remote island with 49 other players seeking survival.',
    genre: 'Shooter',
    price: 0,
    rating: 4.3,
    reviews: 42000000,
    cover_image: 'https://play-lh.googleusercontent.com/1wE91ae_1YIJtIjQ1YJz5RhAajxEpF1TfrXGg7tcrKl90MOnF7XdFj71pw_MSQbyhM5PYz-eRdeBFQBzSGrV=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/1wE91ae_1YIJtIjQ1YJz5RhAajxEpF1TfrXGg7tcrKl90MOnF7XdFj71pw_MSQbyhM5PYz-eRdeBFQBzSGrV=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Garena International',
    isMobile: true,
    original_year: 2017,
    downloads: '1B+',
    tags: ['Battle Royale', 'Fast-Paced', '10-Min Matches'],
    screenshots: [
      'https://play-lh.googleusercontent.com/y18QRycGmsM-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=y18QRycGmsM'
  },
  {
    id: 'candy_crush',
    title: 'Candy Crush Saga',
    description: 'Match and blast colorful candies in this puzzle adventure. Thousands of levels with sweet challenges await.',
    genre: 'Puzzle',
    price: 0,
    rating: 4.6,
    reviews: 38000000,
    cover_image: 'https://play-lh.googleusercontent.com/JvMhIxuwArVmcMReJQB8PIEB1MIQNMGf9j5i914JtkBrHrA55K-nMUIVlYCa7SXAdHtzLtsycEo6NpXeHFxLwvI=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/JvMhIxuwArVmcMReJQB8PIEB1MIQNMGf9j5i914JtkBrHrA55K-nMUIVlYCa7SXAdHtzLtsycEo6NpXeHFxLwvI=w2560-h1440-rw',
    platforms: ['Android', 'iOS', 'PC'],
    developer: 'King',
    isMobile: true,
    original_year: 2012,
    downloads: '1B+',
    tags: ['Match 3', 'Casual', 'Addictive'],
    screenshots: [
      'https://play-lh.googleusercontent.com/W-UwCQlI9KM-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=W-UwCQlI9KM'
  },
  {
    id: 'royal_match',
    title: 'Royal Match',
    description: 'Match 3 puzzle adventure. Help King Robert restore his castle to its former glory in this exciting match-3 puzzle game.',
    genre: 'Puzzle',
    price: 0,
    rating: 4.6,
    reviews: 5200000,
    cover_image: 'https://play-lh.googleusercontent.com/qBdVfwRCsI4KM7qewhJ0AKZKQjyD-DdxPDcdDbsRMhNO9zrwbefggn1vGqRIDZA3fg=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/qBdVfwRCsI4KM7qewhJ0AKZKQjyD-DdxPDcdDbsRMhNO9zrwbefggn1vGqRIDZA3fg=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Dream Games',
    isMobile: true,
    original_year: 2020,
    downloads: '100M+',
    tags: ['Match 3', 'Puzzle', 'Adventure'],
    screenshots: [
      'https://play-lh.googleusercontent.com/iO6wwqq_Y7k-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=iO6wwqq_Y7k'
  },
  {
    id: '8_ball_pool',
    title: '8 Ball Pool',
    description: 'Play pool with friends and players around the world. Win prizes, customize your cues and table, and master trick shots.',
    genre: 'Sports',
    price: 0,
    rating: 4.8,
    reviews: 52000000,
    cover_image: 'https://play-lh.googleusercontent.com/bPz1guJ6FHF3oIOEy3KqwpaDDKO-hLRaZoyzmM8bLFLN8fWm6L0_EuUnkwv9iqPo3Ag=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/bPz1guJ6FHF3oIOEy3KqwpaDDKO-hLRaZoyzmM8bLFLN8fWm6L0_EuUnkwv9iqPo3Ag=w2560-h1440-rw',
    platforms: ['Android', 'iOS', 'PC'],
    developer: 'Miniclip.com',
    isMobile: true,
    original_year: 2010,
    downloads: '500M+',
    tags: ['Billiards', 'Multiplayer', 'Casual'],
    screenshots: [
      'https://play-lh.googleusercontent.com/MkKWx0uVyRw-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=MkKWx0uVyRw'
  },
  {
    id: 'lords_mobile',
    title: 'Lords Mobile: Kingdom Wars',
    description: 'Build an empire and conquer enemies in real-time strategy battles. Command heroes, train troops, and crush your foes.',
    genre: 'Strategy',
    price: 0,
    rating: 4.5,
    reviews: 16000000,
    cover_image: 'https://play-lh.googleusercontent.com/9gTDGNC_Ly7dWNWcfZtnBKdIY8a9REzuWMCC89ycYugXGvWgAPDo4GgnyitrX2LpMqE-1yb_2CDFugre9QVKfg=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/9gTDGNC_Ly7dWNWcfZtnBKdIY8a9REzuWMCC89ycYugXGvWgAPDo4GgnyitrX2LpMqE-1yb_2CDFugre9QVKfg=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'IGG.COM',
    isMobile: true,
    original_year: 2016,
    downloads: '100M+',
    tags: ['4X', 'War Strategy', 'MMO'],
    screenshots: [
      'https://play-lh.googleusercontent.com/rRptqD2wKjw-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=rRptqD2wKjw'
  },
  {
    id: 'township',
    title: 'Township',
    description: 'Build your dream town! Harvest crops, process goods, and sell them to develop your town. Trade with exotic islands.',
    genre: 'Simulation',
    price: 0,
    rating: 4.8,
    reviews: 18000000,
    cover_image: 'https://play-lh.googleusercontent.com/87ZWG0h0ohRprr_B-ikfu66EgiL__wNWROk9yW5xl918h0RSzfAjRC4OnIaXhTux_mRW=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/87ZWG0h0ohRprr_B-ikfu66EgiL__wNWROk9yW5xl918h0RSzfAjRC4OnIaXhTux_mRW=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Playrix',
    isMobile: true,
    original_year: 2013,
    downloads: '100M+',
    tags: ['Farming', 'City Building', 'Casual'],
    screenshots: [
      'https://play-lh.googleusercontent.com/L46PkGz3SqI-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=L46PkGz3SqI'
  },
  {
    id: 'toon_blast',
    title: 'Toon Blast',
    description: 'Blast cubes and create powerful combos in this fun puzzle adventure. Join the Toon gang and solve unique puzzles.',
    genre: 'Puzzle',
    price: 0,
    rating: 4.6,
    reviews: 8900000,
    cover_image: 'https://play-lh.googleusercontent.com/gtbXJIRh-y3vS3885bqy-4y8noqfzFym7Ep47eoZuZs_6wd5lc4L0_sWp66lMmD7Olw=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/gtbXJIRh-y3vS3885bqy-4y8noqfzFym7Ep47eoZuZs_6wd5lc4L0_sWp66lMmD7Olw=w2560-h1440-rw',
    platforms: ['Android', 'iOS'],
    developer: 'Peak Games',
    isMobile: true,
    original_year: 2017,
    downloads: '100M+',
    tags: ['Puzzle', 'Match 3', 'Cartoon'],
    screenshots: [
      'https://play-lh.googleusercontent.com/PDCqvfZIutQ-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=PDCqvfZIutQ'
  },
  {
    id: 'block_blast',
    title: 'Block Blast!',
    description: 'Addictive block puzzle game. Fill lines and clear blocks to beat your high score in this offline puzzle adventure.',
    genre: 'Puzzle',
    price: 0,
    rating: 4.8,
    reviews: 850000,
    cover_image: 'https://play-lh.googleusercontent.com/R0qgNDYYHbRhw6JFsdEbDMqONplEvJx0m0W9wzYVvY3eNF1c2rfBWYjQxW0sLEzFe1E=w526-h296-rw',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&h=1080&fit=crop',
    platforms: ['Android', 'iOS'],
    developer: 'Hungry Studio',
    isMobile: true,
    original_year: 2024,
    downloads: '10M+',
    tags: ['Block Puzzle', 'Offline', 'Casual'],
    screenshots: []
  },
  {
    id: 'minecraft_pe',
    title: 'Minecraft',
    description: 'Build, explore, and survive in infinite randomly-generated worlds. Play with friends cross-platform and create anything you can imagine.',
    genre: 'Sandbox',
    price: 6.99,
    rating: 4.3,
    reviews: 19000000,
    cover_image: 'https://play-lh.googleusercontent.com/27O5tpaYE82W6m30rJ_MX3-UvshlDM6O8oXDxb6GseYW2T7P8UNT19727MGmz-0q3w=w526-h296-rw',
    banner: 'https://play-lh.googleusercontent.com/27O5tpaYE82W6m30rJ_MX3-UvshlDM6O8oXDxb6GseYW2T7P8UNT19727MGmz-0q3w=w2560-h1440-rw',
    platforms: ['Android', 'iOS', 'PC', 'Xbox', 'PlayStation'],
    developer: 'Mojang',
    isMobile: true,
    original_year: 2011,
    downloads: '100M+',
    tags: ['Creative', 'Survival', 'Multiplayer'],
    screenshots: [
      'https://play-lh.googleusercontent.com/BLtLrFNRE-E-h235-rw'
    ],
    trailer_url: 'https://www.youtube.com/watch?v=BLtLrFNRE-E'
  },
  {
    id: 'where_winds_meet',
    title: 'Where Winds Meet',
    description: 'Immersive open-world martial arts action RPG set in ancient China. Master kung fu and explore breathtaking landscapes.',
    genre: 'RPG',
    price: 0,
    rating: 4.2,
    reviews: 450000,
    cover_image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=450&fit=crop',
    banner: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&h=1080&fit=crop',
    platforms: ['Android', 'iOS', 'PC'],
    developer: 'Everstone Studio',
    isMobile: true,
    original_year: 2024,
    downloads: '1M+',
    tags: ['Martial Arts', 'Open World', 'Action'],
    screenshots: [
      'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=800&h=450&fit=crop'
    ]
  },
  {
    id: 'honkai_star_rail_mobile',
    title: 'Honkai: Star Rail',
    description: 'Space fantasy RPG featuring strategic turn-based combat, stunning visuals, and an epic sci-fi storyline across the stars.',
    genre: 'RPG',
    price: 0,
    rating: 4.6,
    reviews: 1800000,
    cover_image: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=800&h=450&fit=crop',
    banner: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=1920&h=1080&fit=crop',
    platforms: ['Android', 'iOS', 'PC'],
    developer: 'HoYoverse',
    isMobile: true,
    aiEnhanced: true,
    original_year: 2023,
    downloads: '50M+',
    tags: ['Turn-Based', 'Space Fantasy', 'Story Rich'],
    screenshots: []
  }
];