import { useEffect, useState } from 'react';
import { ArrowRight, Check, Crown, Gem, Hammer, Lock, Plus, Shield, Sparkles } from 'lucide-react';
import { Action, Costs, Empty, Meter, PowerChange, RankTrack, Review, SectionTitle } from './CardDetailPrimitives';
import { canAfford, format, STAT_LABELS, words } from './cardDetailModel';

const SECTIONS=[['level','Level & stats',Sparkles],['enchant','Enchantment',Gem],['divine','Divine stage',Shield],['ascension','Ascension',Crown]];
export default function CardUpgradePanel({detail,section,onSection}) {
  return <div className="cdw-upgrade"><div className="cdw-upgrade-nav" aria-label="Upgrade disciplines">{SECTIONS.map(([id,label,Icon])=><button key={id} aria-pressed={section===id} onClick={()=>onSection(id)}><Icon size={17}/><span>{label}</span></button>)}</div>
    {section==='level'&&<LevelPanel detail={detail}/>}
    {section==='enchant'&&<EnchantPanel detail={detail}/>}
    {section==='divine'&&<DivinePanel detail={detail}/>}
    {section==='ascension'&&<AscensionPanel detail={detail}/>}
  </div>;
}
const lockedReason=state=>state.userCard.trade_status==='locked_in_trade'?'Finish the trade or cancel the listing first.':'';
function LevelPanel({detail}) {
  const {state,busy,act}=detail,p=state.progression,w=state.workshop,materials=state.materials;
  const [stat,setStat]=useState('attack');
  const quote=w.enhance[stat],cap=p.level>=p.max_level,lock=lockedReason(state);
  const levelReason=lock||(cap?'Ascend this card to increase its level cap.':p.xp<p.xp_to_next?'Earn '+format(p.xp_to_next-p.xp)+' more XP.':'');
  return <><SectionTitle eyebrow="Discipline I · Advancement" title="Every level leaves a mark.">Train with skill catalysts, gain levels, then choose how your attributes grow.</SectionTitle>
    <div className="cdw-two-col"><section className="cdw-panel"><span className="cdw-eyebrow">Current level</span><div className="cdw-large-number">{p.level}<span>/ {p.max_level}</span></div><Meter value={p.xp} max={p.xp_to_next} label="Card experience"/><p>Each level grants <b>1 stat point</b> and <b>1 skill point</b>.</p>{!cap&&<PowerChange before={p.power_score} after={w.level.power_after}/>}<Action busy={busy} reason={levelReason} onClick={()=>act('levelUp')}>{cap?'Level cap reached':'Advance to level '+(Number(p.level)+1)}</Action></section>
    <section className="cdw-panel"><span className="cdw-eyebrow">Training ritual</span><h3>Ignite a skill catalyst</h3><p>Add <b>{format(w.training.xp_gain)} XP</b> to this card. Materials are consumed when training succeeds.</p><Costs costs={w.training.costs} materials={materials}/><Action busy={busy} reason={lock||(cap?'Ascend before training further.':!canAfford(materials,w.training.costs)?'You need a skill catalyst.':'')} onClick={()=>act('train',{sessions:1})}>Train · +{format(w.training.xp_gain)} XP</Action></section></div>
    <section className="cdw-panel"><div className="cdw-line-heading"><h3>Refine your attributes</h3><span>{format(p.stat_points)} unspent points</span></div><div className="cdw-stat-picker">{Object.entries(STAT_LABELS).map(([key,label])=><button key={key} aria-pressed={stat===key} onClick={()=>setStat(key)}><span>{label}</span><strong>{format(p.effective_stats?.[key])}</strong></button>)}</div>
    <div className="cdw-two-col"><div><h4>Allocate a level point</h4><p>Spend one stat point to add <b>+1 {STAT_LABELS[stat].toLowerCase()}</b> before growth multipliers.</p><Action secondary busy={busy} reason={lock||(p.stat_points<1?'Gain a level to earn a stat point.':'')} onClick={()=>act('allocateStat',{stat})}>Allocate to {STAT_LABELS[stat]}</Action></div><div><h4>Material enhancement</h4><p>Forge <b>+{quote.gain} {STAT_LABELS[stat].toLowerCase()}</b> before growth multipliers.</p><Costs costs={quote.costs} materials={materials}/><PowerChange before={p.power_score} after={quote.power_after}/><Action busy={busy} reason={lock||(!canAfford(materials,quote.costs)?'Gather the required materials.':'')} onClick={()=>act('enhance',{stat})}>Enhance {STAT_LABELS[stat]}</Action></div></div></section>
  </>;
}
function EnchantPanel({detail}) {
  const {state,busy,act}=detail,p=state.progression,w=state.workshop,materials=state.materials;
  const [kind,setKind]=useState('gem'),[selected,setSelected]=useState(''),[review,setReview]=useState('');
  useEffect(()=>setReview(''),[p.revision]);
  const installed=p.enchantments||[],recipes=w.recipes.filter(r=>r.socket_type===kind);
  const recipe=recipes.find(r=>r.id===selected)||recipes[0],o=w.over_enchant,lock=lockedReason(state);
  const reason=lock||(!recipe?'No compatible recipe is available.':installed.some(e=>e.id===recipe.id)?'This infusion is already installed.':!Number.isSafeInteger(recipe.slot_cost)||recipe.slot_cost<1?'This recipe needs a valid socket cost.':w.sockets.used+recipe.slot_cost>w.sockets.total?'Not enough free sockets. Advance your divine stage or ascend.':!canAfford(materials,recipe.costs)?'Gather the required materials.':'');
  const overReason=lock||((p.over_enchant_rank||0)>=o.max?'Maximum enchantment rank reached.':!installed.length?'Install an infusion before over-enchanting.':!canAfford(materials,o.costs)?'Gather the required adaptive shards.':'');
  return <><SectionTitle eyebrow="Discipline II · Infusion" title="Give your card a new edge." aside={<span className="cdw-count">{w.sockets.used} / {w.sockets.total} sockets</span>}>Install cores, gems and runes. Over-enchantment strengthens an infused card with a chance of failure.</SectionTitle>
    <section className="cdw-socket-strip" aria-label="Installed enchantments">{installed.map(e=><div key={e.id} data-filled="true"><Gem size={22}/><div><strong>{e.name}</strong><span>{words(e.socket_type||'gem')} · {e.slot_cost||1} socket{(e.slot_cost||1)>1?'s':''}{e.overcharged?' · Overcharged':''}</span></div></div>)}{Array.from({length:Math.max(0,w.sockets.total-w.sockets.used)},(_,i)=><div key={'empty'+i}><Plus size={20}/><div><strong>Open socket</strong><span>Ready for an infusion</span></div></div>)}</section>
    <div className="cdw-segments" aria-label="Socket recipe type">{['core','gem','rune'].map(type=><button key={type} aria-pressed={kind===type} onClick={()=>{setKind(type);setSelected('');setReview('');}}>{words(type)} recipes</button>)}</div>
    <div className="cdw-recipe-layout"><div className="cdw-recipes">{recipes.length?recipes.map(r=><button key={r.id} aria-pressed={recipe?.id===r.id} onClick={()=>{setSelected(r.id);setReview('');}}><Gem size={18}/><span><strong>{r.name}</strong><small>{r.slot_cost} socket{r.slot_cost>1?'s':''} · {words(r.element||r.socket_type)}</small></span>{installed.some(e=>e.id===r.id)?<Check size={14}/>:<ArrowRight size={13}/>}</button>):<Empty icon={Gem} title="No compatible recipes">Recipes that support this card type will appear here when available.</Empty>}</div>
    {recipe&&<section className="cdw-panel"><span className="cdw-eyebrow">Selected infusion</span><h3>{recipe.name}</h3><p>{recipe.description||'Adds the following modifiers to your card.'}</p><div className="cdw-modifiers">{Object.entries(recipe.modifiers||{}).map(([key,value])=><span key={key}>{words(key)} <strong>{Number(value)>0?'+':''}{format(value)}</strong></span>)}</div><Costs costs={recipe.costs} materials={materials}/>{review==='infuse'?<Review title={'Infuse '+recipe.name+'?'} onCancel={()=>setReview('')} busy={busy} disabled={Boolean(reason)} label="Confirm infusion" onConfirm={async()=>{if(await act('enchant',{enchantmentId:recipe.id,socketType:recipe.socket_type}))setReview('');}}><p>Consumes the materials above and permanently uses {recipe.slot_cost} socket{recipe.slot_cost>1?'s':''}. Installed infusions cannot currently be removed.</p></Review>:<Action busy={busy} reason={reason} onClick={()=>setReview('infuse')}>Review infusion</Action>}</section>}</div>
    <section className="cdw-panel cdw-over-enchant"><div className="cdw-line-heading"><h3>Over-enchantment</h3><span>Rank +{p.over_enchant_rank||0} / +{o.max}</span></div><RankTrack value={p.over_enchant_rank||0} label="Enchantment ranks"/><div className="cdw-two-col"><div><div className="cdw-large-number">{o.success_chance}<span>% chance</span></div><p>A successful attempt adds <b>+{o.gain}</b> to all five attributes before growth. Failure keeps the card intact but still consumes the materials.</p><Meter label="Stability" value={p.over_enchant_stability??100} max={100}/><p className="cdw-footnote">Stability loss: {o.stability_loss_success} on success, {o.stability_loss_failure} on failure. Current success chance depends on rank, stage and Enchanter Focus.</p></div><div><Costs costs={o.costs} materials={materials}/>{review==='over'?<Review title={'Attempt rank +'+o.next_rank+'?'} onCancel={()=>setReview('')} busy={busy} disabled={Boolean(overReason)} label="Attempt over-enchant" onConfirm={async()=>{if(await act('overEnchant'))setReview('');}}><p>{o.success_chance}% success chance. Shards are spent on both success and failure.</p></Review>:<Action busy={busy} reason={overReason} onClick={()=>setReview('over')}>Review over-enchantment</Action>}</div></div></section>
  </>;
}
function DivinePanel({detail}) {
  const {state,busy,act}=detail,p=state.progression,w=state.workshop.divine;
  const [mode,setMode]=useState('cards'),[selected,setSelected]=useState([]),[review,setReview]=useState(false);
  const candidates=state.compatibleCards||[];
  const chosen=candidates.filter(c=>selected.includes(c.id));
  useEffect(()=>{setReview(false);setSelected([]);},[p.revision]);
  const capped=p.stage>=w.max;
  const reason=lockedReason(state)||(capped?'Maximum divine stage reached.':mode==='wildcard'?!canAfford(state.materials,w.wildcard_costs)?'You need one wildcard.':'':chosen.length!==w.needed?'Select '+w.needed+' compatible inventory entries.':'');
  return <><SectionTitle eyebrow="Discipline III · Evolution" title="Advance your divine stage.">Offer compatible cards or a wildcard to evolve this card. Each new stage grants one skill point and raises its growth multiplier.</SectionTitle><RankTrack value={p.stage} label="Divine stages"/>
    {capped?<Empty icon={Crown} title="The final divine stage">This card has reached stage V. Continue developing its level, enchantments and skill paths.</Empty>:<>
    <div className="cdw-transition"><div><span>Current stage</span><strong>{p.stage}</strong></div><ArrowRight/><div><span>Next divine stage</span><strong>{w.next_stage}</strong></div><div><span>Power after evolution</span><strong>{format(w.power_after)}</strong></div></div>
    <div className="cdw-segments" aria-label="Fusion offering">{[['cards','Compatible cards'],['wildcard','Use a wildcard']].map(([id,label])=><button key={id} aria-pressed={mode===id} onClick={()=>{setMode(id);setReview(false);}}>{label}</button>)}</div>
    {mode==='cards'?<><div className="cdw-line-heading"><h3>Choose your offerings</h3><span>{chosen.length} / {w.needed} selected</span></div><p>Only compatible, unequipped cards from your inventory appear here. Selected inventory entries are permanently consumed, including any stacked copies.</p><div className="cdw-offerings">{candidates.map(c=><button key={c.id} aria-pressed={selected.includes(c.id)} disabled={busy||Boolean(lockedReason(state))||(!selected.includes(c.id)&&chosen.length>=w.needed)} onClick={()=>{setReview(false);setSelected(ids=>ids.includes(c.id)?ids.filter(id=>id!==c.id):[...ids,c.id]);}}>{c.card_image?<img src={c.card_image} alt=""/>:<Gem size={23}/>}<span><strong>{c.card_name}</strong><small>{c.card_rarity} · {c.quantity??1} {(c.quantity??1)>1?'copies':'copy'}</small></span><span className="cdw-select-mark">{selected.includes(c.id)?<Check size={14}/>:<Plus size={14}/>}</span></button>)}</div>{!candidates.length&&<Empty icon={Shield} title="No compatible offerings yet">Collect more cards from this game or use a wildcard. Starter, equipped and reserved cards cannot be offered.</Empty>}</>:<section className="cdw-panel"><h3>Preserve your other cards</h3><p>One wildcard replaces all required card offerings for this stage.</p><Costs costs={w.wildcard_costs} materials={state.materials}/></section>}
    {review?<Review title={'Evolve to divine stage '+w.next_stage+'?'} busy={busy} disabled={Boolean(reason)} onCancel={()=>setReview(false)} label="Confirm divine evolution" onConfirm={async()=>{if(await act('combine',mode==='wildcard'?{useWildcard:true}:{sacrificeUserCardIds:chosen.map(c=>c.id)}))setReview(false);}}><p>{mode==='wildcard'?'One wildcard will be permanently consumed.':'The following inventory entries and all their stacked copies will be permanently consumed:'}</p>{mode==='cards'&&<ul>{chosen.map(c=><li key={c.id}>{c.card_name} × {c.quantity??1}</li>)}</ul>}<PowerChange before={p.power_score} after={w.power_after}/><p>Your main card remains and gains one divine stage and one skill point.</p></Review>:<Action busy={busy} reason={reason} onClick={()=>setReview(true)}>Review divine evolution</Action>}
    </>}
  </>;
}
function AscensionPanel({detail}) {
  const {state,busy,act}=detail,p=state.progression,w=state.workshop.ascension;
  const [review,setReview]=useState(false);
  useEffect(()=>setReview(false),[p.revision]);
  const capped=p.ascension>=w.max;
  const reason=lockedReason(state)||(capped?'Maximum ascension reached.':p.level<p.max_level?'Reach level '+p.max_level+' before ascending.':!canAfford(state.materials,w.costs)?'Gather the required ascension cores.':'');
  return <><SectionTitle eyebrow="Discipline IV · Transcendence" title="Beyond the current limit.">Ascension raises your card’s level cap and opens another chapter of growth.</SectionTitle><RankTrack value={p.ascension||0} label="Ascension ranks"/>
    {capped?<Empty icon={Crown} title="Fully ascended">All five ascensions are complete. Continue refining this card’s remaining progression paths.</Empty>:<section className="cdw-panel cdw-ascension"><Crown size={38}/><div className="cdw-transition"><div><span>Level cap</span><strong>{p.max_level}</strong></div><ArrowRight/><div><span>New level cap</span><strong>{w.next_cap}</strong></div><div><span>Skill points gained</span><strong>+2</strong></div></div><PowerChange before={p.power_score} after={w.power_after}/><p>Your current level is retained. Card XP resets to zero. Ascension also contributes to growth and the available socket count.</p><Costs costs={w.costs} materials={state.materials}/>{review?<Review title={'Unlock ascension '+w.next_rank+'?'} busy={busy} disabled={Boolean(reason)} onCancel={()=>setReview(false)} label="Confirm ascension" onConfirm={async()=>{if(await act('ascend'))setReview(false);}}><p>Consumes {w.costs.ascension_core} ascension core{w.costs.ascension_core>1?'s':''}, resets XP to zero and increases the level cap to {w.next_cap}.</p></Review>:<Action busy={busy} reason={reason} onClick={()=>setReview(true)}>Review ascension</Action>}</section>}
  </>;
}
