import React, { useState } from 'react';

export default function ProgressionLevel({ state, act, disabled }) {
  const [sessions, setSessions] = useState(1);
  const p = state.progression;
  const quantity = (type) => state.materials.filter(m => m.material_type === type).reduce((sum,m) => sum + m.quantity,0);
  return <div className="grid lg:grid-cols-2 gap-5">
    <section className="cr-panel"><p className="cr-label">Training · earn card XP</p><h3 className="mt-2 text-xl">Level {p.level} / {p.max_level}</h3><p className="text-sm text-muted-foreground my-4">Each session consumes 1 Skill Catalyst and grants {50 + p.stage * 10} XP.</p><label className="text-xs text-muted-foreground">Training sessions<select aria-label="Training sessions" className="cr-input mt-2" value={sessions} onChange={e => setSessions(Number(e.target.value))}>{[1,3,5,10].map(n => <option key={n} value={n}>{n} session{n > 1 ? 's' : ''}</option>)}</select></label><p className="text-xs text-muted-foreground mt-3">Available: {quantity('skill_catalyst')} Skill Catalysts</p><button className="cr-action mt-4" disabled={disabled || quantity('skill_catalyst') < sessions} onClick={() => act('train',{sessions})}>Train card</button></section>
    <section className="cr-panel"><p className="cr-label">Leveling</p><h3 className="mt-2 text-xl">{p.xp} / {p.xp_to_next} XP</h3><progress className="mt-5" value={Math.min(p.xp,p.xp_to_next)} max={p.xp_to_next}/><p className="my-4 text-sm text-muted-foreground">Spend {p.xp_to_next} XP to scale base stats and earn 1 Skill Point.</p><button className="cr-action" disabled={disabled || p.xp < p.xp_to_next || p.level >= p.max_level} onClick={() => act('levelUp')}>Level up</button><p className="mt-3 text-xs text-muted-foreground">{p.level >= p.max_level ? 'Stage or ascend to raise the level cap.' : `${Math.max(0,p.xp_to_next - p.xp)} more XP needed.`}</p></section>
    <section className="cr-panel lg:col-span-2"><p className="cr-label">Ascension {p.ascension} / 5</p><p className="my-4 text-sm text-muted-foreground">At the level cap, consume {p.ascension + 1} Ascension Core(s) to raise the cap by 10 and earn 2 Skill Points. Remaining card XP is reset.</p><button className="cr-action" disabled={disabled || p.level < p.max_level || p.ascension >= 5 || quantity('ascension_core') < p.ascension + 1} onClick={() => act('ascend')}>Ascend card</button></section>
  </div>;
}