import React from 'react';
import { Activity, Shield, Sparkles } from 'lucide-react';

export default function ProgressionRecord({ state, card }) {
  const p = state.progression;
  const days = Array.from({ length: 14 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 13 + i); return d.toISOString().slice(0, 10); });
  return <div className="space-y-5" data-testid="progression-record">
    <section className="cr-panel"><p className="cr-label">The Record · Saved card state</p><h2 className="mt-2 text-2xl font-semibold">{card.title}</h2><p className="mt-2 text-sm text-muted-foreground">{card.description || `An earned ${(state.userCard.card_type || 'card').toLowerCase()} from ${state.userCard.game_name || 'your collection'}.`}</p>
      <div className="mt-5 grid grid-cols-2 lg:grid-cols-4 gap-4">{[['Power', p.power_score], ['Level', `${p.level} / ${p.max_level}`], ['Tier / Stage', p.stage], ['Perk slots', `${p.active_perks.length} / ${p.perk_slots}`]].map(([label,value]) => <div key={label}><p className="cr-label">{label}</p><strong className="block mt-2 text-xl font-medium">{value}</strong></div>)}</div>
      <div className="mt-5 flex justify-between text-xs text-muted-foreground"><span>Card XP</span><span>{p.xp} / {p.xp_to_next}</span></div><progress className="mt-2" value={Math.min(p.xp, p.xp_to_next)} max={p.xp_to_next} />
    </section>
    <div className="grid md:grid-cols-2 gap-5"><section className="cr-panel"><p className="cr-label">Scaled attributes</p><div className="mt-4 space-y-3">{Object.entries(p.scaled_stats || {}).map(([key,value]) => <div key={key} className="flex justify-between text-sm"><span className="capitalize text-muted-foreground">{key}</span><strong>{value}</strong></div>)}</div><p className="text-xs text-muted-foreground mt-4">Includes level, stage, enchantments, and card condition.</p></section>
      <section className="cr-panel"><p className="cr-label">Status & utility</p><p className="flex items-center gap-2 mt-4 text-primary"><Shield size={16}/>{p.condition} · {p.over_enchant_stability}% stability</p><p className="mt-3 text-sm">Enchantment +{p.over_enchant_rank} · Ascension {p.ascension}</p><p className="mt-3 text-sm text-muted-foreground">Reward type: {state.userCard.card_type}</p><p className="mt-2 text-xs text-muted-foreground">{state.userCard.is_equipped ? 'Equipped — unequip to modify' : state.userCard.trade_status === 'locked_in_trade' ? 'Reserved in trade — close listing to modify' : 'Available in your inventory'}</p><p className="mt-4 text-xs text-muted-foreground">Earned {state.userCard.unlocked_date ? new Date(state.userCard.unlocked_date).toLocaleDateString() : 'date not recorded'}</p></section></div>
    <section className="cr-panel"><p className="cr-label flex items-center gap-2"><Sparkles size={14}/> Active perk loadout</p><div className="mt-4 flex flex-wrap gap-2">{p.active_perks.length ? p.active_perks.map(id => <span key={id} className="rounded border border-primary/30 px-3 py-2 text-xs text-primary">{state.skillTree.find(node => node.id === id)?.name || id}</span>) : <p className="text-sm text-muted-foreground">No perks assigned. Unlock and assign them in the Skill Tree.</p>}</div></section>
    <section className="cr-panel"><p className="cr-label flex items-center gap-2"><Activity size={14}/> Progression activity · last 30 events</p><div className="mt-4 grid grid-cols-7 sm:grid-cols-[repeat(14,minmax(0,1fr))] gap-2">{days.map(day => { const count = state.events.filter(e => e.created_date?.slice(0,10) === day).length; return <div key={day} title={`${day}: ${count} events`} className={`h-8 rounded border ${count ? 'bg-primary/30 border-primary/40' : 'bg-muted border-border'}`} aria-label={`${day}: ${count} progression events`}/>; })}</div><ul className="mt-4 space-y-3">{state.events.slice(0,6).map(event => <li key={event.id} className="text-xs"><span>{event.summary}</span><time className="block mt-1 text-muted-foreground">{new Date(event.created_date).toLocaleString()}</time></li>)}</ul></section>
    <section className="cr-panel"><p className="cr-label">Gameplay telemetry</p><div className="mt-4 grid grid-cols-3 gap-3">{['Kills','Accuracy','Win rate'].map(label => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1">—</p></div>)}</div><p className="mt-3 text-xs text-muted-foreground">No verified card-linked gameplay feed is connected yet. Progression updates live; gameplay statistics are not simulated.</p></section>
  </div>;
}