import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
const dir=path.resolve('node_modules/.cache/creator-ui');fs.mkdirSync(dir,{recursive:true});
const dom=new JSDOM('<div id="root"></div>',{url:'https://atomxeveos.base44.app/gameview'});
for(const key of ['window','document','HTMLElement','Element','CustomEvent','Event','MouseEvent','KeyboardEvent'])globalThis[key]=dom.window[key];
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
globalThis.__catalog={assets:[{id:'hair-f',name:'Braided hair',slot:'hair',gender:'female',rig_id:'artemis-v1',binding:'skinned',published:true,file_url:'/models/test-hair.glb',tint_materials:['Hair']},{id:'outfit-f',name:'Archer linen',slot:'outfit',gender:'female',rig_id:'artemis-v1',binding:'skinned',published:true,file_url:'/models/test-outfit.glb'},{id:'hair-m',name:'Male crop',slot:'hair',gender:'male',rig_id:'getsuga-v1',binding:'skinned',published:true,file_url:'/models/male-hair.glb'}],canManage:false};
let saved;
globalThis.__saveAppearance=async config=>{saved=config;return {...config,id:'avatar-test'};};
await build({entryPoints:['src/components/onboarding/AvatarAppearanceDialog.jsx'],outfile:dir+'/dialog.mjs',bundle:true,format:'esm',platform:'node',packages:'external',jsx:'automatic',loader:{'.css':'empty'},plugins:[{name:'creator-fixtures',setup(b){
 b.onResolve({filter:/useCustomizationCatalog$/},()=>({path:'catalog',namespace:'fixture'}));
 b.onResolve({filter:/GenesisModelPreview$/},()=>({path:'preview',namespace:'fixture'}));
 b.onResolve({filter:/saveAppearance$/},()=>({path:'save',namespace:'fixture'}));
 b.onResolve({filter:/CustomizationAssetManager$/},()=>({path:'workshop',namespace:'fixture'}));
 b.onLoad({filter:/.*/,namespace:'fixture'},a=>({loader:'js',contents:a.path==='catalog'?'export function useCustomizationCatalog(){return {data:globalThis.__catalog,isError:false};}':a.path==='save'?'export async function saveAppearance(c){return globalThis.__saveAppearance(c)}':a.path==='workshop'?'export default function Workshop(){return null;}':`import React,{useEffect,useRef} from 'react';export default function Preview(p){const latest=useRef(p);latest.current=p;useEffect(()=>{latest.current.onCapabilities({customization:{iris:true,shapes:[],meshNames:[],boneNames:[]},weapon:true});latest.current.onCustomizationState({loading:false,error:''});},[p.config.gender]);return React.createElement('div',{'data-preview-gender':p.config.gender});}`}));
}}]});
const {default:Dialog}=await import('file://'+dir+'/dialog.mjs');
const React=await import('react'),{createRoot}=await import('react-dom/client'),{act}=React;
test('creator switches models, filters layers, previews selections and saves them together',async()=>{
 const root=createRoot(document.getElementById('root'));let closed=0;
 await act(async()=>root.render(React.createElement(Dialog,{initialAvatar:{gender:'female'},onClose:()=>closed++})));
 const button=text=>[...document.querySelectorAll('button')].find(b=>b.textContent.replace(/\s+/g,' ').trim()===text);
 const click=async node=>{assert(node,'button exists');await act(async()=>node.dispatchEvent(new MouseEvent('click',{bubbles:true})));};
 assert.equal(document.querySelector('[data-preview-gender]').dataset.previewGender,'female');
 assert(document.querySelector('input[aria-label="Chest size"]').disabled,'Unsupported anatomy must not pretend to deform the mesh');
 await click(button('Face03')||[...document.querySelectorAll('.creator-navigation button')].find(b=>b.textContent.includes('Face')));
 await click(document.querySelector('[aria-label="Eye color preset 2"]'));
 await click([...document.querySelectorAll('.creator-navigation button')].find(b=>b.textContent.includes('Hair')));
 assert(document.body.textContent.includes('Braided hair'));assert(!document.body.textContent.includes('Male crop'));
 await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('Braided hair')));
 await click(document.querySelector('[aria-label="Hair color preset 4"]'));
 await click([...document.querySelectorAll('.creator-navigation button')].find(b=>b.textContent.includes('Wardrobe')));
 await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('Archer linen')));
 await click(button('Save appearance'));
 assert.equal(saved.gender,'female');assert.equal(saved.eye_tint_enabled,true);assert.equal(saved.eye_color,'#98663b');
 assert.deepEqual(saved.selected_assets,{hair:'hair-f',outfit:'outfit-f'});assert.equal(saved.customization_assets.length,2);assert.equal(saved.hair_color,'#a36a3b');assert.equal(closed,1);
 await click([...document.querySelectorAll('.creator-navigation button')].find(b=>b.textContent.includes('Body')));
 await click([...document.querySelectorAll('button')].find(b=>b.textContent.includes('Getsuga')));
 assert.equal(document.querySelector('[data-preview-gender]').dataset.previewGender,'male');
 await click(button('Save appearance'));assert.equal(saved.gender,'male');assert.deepEqual(saved.selected_assets,{});
 await act(async()=>root.unmount());
});
