// Rich developer data for the Dev Storefront page

export const DEVELOPERS = [
  {
    id: 'neon-studios',
    name: 'Neon Studios',
    tagline: 'Crafting immersive cyberpunk experiences',
    description: 'Founded in 2019, Neon Studios is a boutique studio focused on narrative-driven cyberpunk worlds. Their team blends film-industry cinematographers with veteran game engineers to deliver story-rich, visually stunning experiences.',
    logo: 'https://images.unsplash.com/photo-1599305445671-ac291c95aaa9?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1920&h=600&fit=crop',
    accentColor: 'cyan',
    founded: 2019,
    teamSize: 42,
    location: 'Tokyo, Japan',
    gamesReleased: 8,
    followers: 124000,
    socials: { website: 'https://neonstudios.dev', twitter: '@neonstudios' },
    releasedGames: [
      { title: 'Neon Protocol', genre: 'Action RPG', year: 2024, cover: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=500&fit=crop', description: 'The original cyberpunk RPG that put Neon Studios on the map. Explore Neo-Tokyo in a branching narrative.' },
      { title: 'Ghost in the Grid', genre: 'Stealth', year: 2022, cover: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=400&h=500&fit=crop', description: 'A stealth-action game set in a digital underworld. Hack, sneak, and survive.' },
      { title: 'Synthwave Dreams', genre: 'Visual Novel', year: 2021, cover: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=500&fit=crop', description: 'A narrative-driven visual novel exploring identity in a digitized future.' },
    ],
    inDevelopment: [
      {
        title: 'Neon Protocol 2',
        genre: 'Action RPG',
        status: 'Alpha',
        progress: 67,
        cover: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=500&fit=crop',
        description: 'A sequel to the hit cyberpunk RPG. New districts, deeper faction system, and a redesigned combat engine.',
        releaseWindow: 'Q2 2027',
        features: ['Open-world Neo-Tokyo', 'Branching faction storylines', 'Customizable augmentations'],
      },
      {
        title: 'Synthwave Racer',
        genre: 'Racing',
        status: 'Pre-Alpha',
        progress: 23,
        cover: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&h=500&fit=crop',
        description: 'High-speed racing through neon-lit highways with a dynamic synthwave soundtrack.',
        releaseWindow: 'Q4 2027',
        features: ['48 tracks', 'Online multiplayer', 'Custom vehicle builder'],
      },
    ],
    customCards: [
      { name: 'Chrome Samurai', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 8200 },
      { name: 'Neon Dragon', rarity: 'Mythic', art: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=300&h=420&fit=crop', power: 9500 },
      { name: 'Ghost Protocol', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&h=420&fit=crop', power: 6400 },
    ],
    updates: [
      { date: 'Jul 10, 2026', title: 'Neon Protocol 2 — Alpha Build 0.4', body: 'Added the Kabukicho district with 12 new quests. Combat flow improvements and new augmentation system.' },
      { date: 'Jun 28, 2026', title: 'Dev Diary #14 — Sound Design', body: 'Lead audio designer Yuki breaks down the adaptive synthwave system that reacts to player actions in real time.' },
      { date: 'Jun 15, 2026', title: 'Community Card Drop', body: 'Three new community cards released for Neon Protocol. Collect them all to unlock the hidden Chrome Samurai variant.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '8' },
      { label: 'Active Projects', value: '2' },
      { label: 'Community Cards', value: '24' },
      { label: 'Dev Awards', value: '3' },
    ],
  },
  {
    id: 'phantom-games',
    name: 'Phantom Games',
    tagline: 'Masters of action-packed adventures',
    description: 'Phantom Games has been delivering adrenaline-fueled action titles since 2015. Known for their fluid combat systems and expansive open worlds, the studio pushes the boundaries of real-time physics and enemy AI.',
    logo: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=1920&h=600&fit=crop',
    accentColor: 'orange',
    founded: 2015,
    teamSize: 78,
    location: 'Los Angeles, USA',
    gamesReleased: 12,
    followers: 289000,
    socials: { website: 'https://phantomgames.io', twitter: '@phantomgames' },
    releasedGames: [
      { title: 'Phantom Blade', genre: 'Action RPG', year: 2024, cover: 'https://images.unsplash.com/photo-1551103782-8ab07d457281?w=400&h=500&fit=crop', description: 'The original spirit-blade action RPG. Master phantom energy combos across 12 bosses.' },
      { title: 'Last Stand', genre: 'Survival', year: 2022, cover: 'https://images.unsplash.com/photo-1509248961158-e54f69343a01?w=400&h=500&fit=crop', description: 'A post-apocalyptic survival game. Build, scavenge, and survive against the horde.' },
      { title: 'Storm Front', genre: 'Strategy', year: 2020, cover: 'https://images.unsplash.com/photo-1518182170546-0766ba6f0f2f?w=400&h=500&fit=crop', description: 'Real-time strategy in a war-torn fantasy realm. Command armies and forge alliances.' },
      { title: 'Shadow Strike', genre: 'Stealth Action', year: 2018, cover: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&h=500&fit=crop', description: 'A ninja stealth-action game with 30 missions and a deep parkour movement system.' },
    ],
    inDevelopment: [
      {
        title: 'Phantom Blade: Awakening',
        genre: 'Action Adventure',
        status: 'Beta',
        progress: 84,
        cover: 'https://images.unsplash.com/photo-1551103782-8ab07d457281?w=400&h=500&fit=crop',
        description: 'A souls-like action game with a unique spirit-blade combat system. Players harness phantom energy to chain devastating combos.',
        releaseWindow: 'Q1 2027',
        features: ['Spirit-blade combat', '12 unique bosses', 'Online co-op dungeons'],
      },
      {
        title: 'Last Stand: Outbreak',
        genre: 'Survival Horror',
        status: 'Concept',
        progress: 12,
        cover: 'https://images.unsplash.com/photo-1509248961158-e54f69343a01?w=400&h=500&fit=crop',
        description: 'A zombie survival game where every decision matters. Build your fortress, scavenge at night, and survive the horde.',
        releaseWindow: '2028',
        features: ['Procedural city generation', 'Base building', 'Day/night threat cycle'],
      },
      {
        title: 'Storm Raiders',
        genre: 'Strategy',
        status: 'Pre-Alpha',
        progress: 31,
        cover: 'https://images.unsplash.com/photo-1518182170546-0766ba6f0f2f?w=400&h=500&fit=crop',
        description: 'Real-time strategy set in a war-torn fantasy realm. Command armies, forge alliances, and conquer the storm.',
        releaseWindow: 'Q3 2027',
        features: ['4X RTS hybrid', 'Dynamic weather warfare', '8 playable factions'],
      },
    ],
    customCards: [
      { name: 'Phantom Blade', rarity: 'Mythic', art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=420&fit=crop', power: 9800 },
      { name: 'Storm Caller', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=300&h=420&fit=crop', power: 7600 },
      { name: 'Survivor', rarity: 'Rare', art: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=300&h=420&fit=crop', power: 5200 },
      { name: 'Warlord', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 6900 },
    ],
    updates: [
      { date: 'Jul 8, 2026', title: 'Phantom Blade — Beta Open!', body: 'Beta access is now open to all community members. Try the first three bosses and give us your feedback.' },
      { date: 'Jun 22, 2026', title: 'Dev Stream — Combat Deep Dive', body: 'Watch our lead combat designer break down the spirit-blade combo system and phantom dodging mechanics.' },
      { date: 'Jun 1, 2026', title: 'Storm Raiders Faction Reveal', body: 'Introducing the first four factions: Ironclad, Stormborn, Verdant, and Ashen. Each with unique units and playstyles.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '12' },
      { label: 'Active Projects', value: '3' },
      { label: 'Community Cards', value: '32' },
      { label: 'Dev Awards', value: '7' },
    ],
  },
  {
    id: 'ethereal-studios',
    name: 'Ethereal Studios',
    tagline: 'Pioneering next-gen RPG experiences',
    description: 'Ethereal Studios is an RPG powerhouse founded by genre veterans. They specialize in deep, choice-driven narratives with branching consequences that ripple across entire game worlds. Their proprietary dialogue engine powers some of the most complex NPC interactions in the industry.',
    logo: 'https://images.unsplash.com/photo-1633409361618-c73427e4e85f?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1920&h=600&fit=crop',
    accentColor: 'purple',
    founded: 2012,
    teamSize: 120,
    location: 'Warsaw, Poland',
    gamesReleased: 15,
    followers: 512000,
    socials: { website: 'https://ethereal.gg', twitter: '@etherealdev' },
    releasedGames: [
      { title: 'Realms of Aetheria', genre: 'Open-World RPG', year: 2024, cover: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=400&h=500&fit=crop', description: 'A massive open-world RPG with 6 playable origin stories and a living economy.' },
      { title: 'Chronicles of the Void', genre: 'Narrative RPG', year: 2021, cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=500&fit=crop', description: 'A story-first RPG set in a dying universe with branching dialogue and deep companion relationships.' },
      { title: 'Kingdoms Reborn', genre: 'Strategy RPG', year: 2019, cover: 'https://images.unsplash.com/photo-1518182170546-0766ba6f0f2f?w=400&h=500&fit=crop', description: 'A tactical RPG with base building and a dynamic political system.' },
      { title: 'Eternal Quest', genre: 'JRPG', year: 2016, cover: 'https://images.unsplash.com/photo-1551103782-8ab07d457281?w=400&h=500&fit=crop', description: 'A classic turn-based RPG with 80+ hours of content and a beloved soundtrack.' },
    ],
    inDevelopment: [
      {
        title: 'Realms of Aetheria',
        genre: 'Open-World RPG',
        status: 'Beta',
        progress: 78,
        cover: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=400&h=500&fit=crop',
        description: 'A massive open-world RPG with 6 playable origin stories, a living economy, and a world that reacts to every choice you make.',
        releaseWindow: 'Q2 2027',
        features: ['6 origin stories', 'Living economy system', '100+ hours of content'],
      },
      {
        title: 'Whispers of the Void',
        genre: 'Narrative RPG',
        status: 'Pre-Alpha',
        progress: 28,
        cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=500&fit=crop',
        description: 'A story-first RPG set in a dying universe. Every conversation matters as you uncover the truth behind the Void.',
        releaseWindow: '2028',
        features: ['Branching dialogue engine', 'Companion relationship system', 'No filler quests'],
      },
    ],
    customCards: [
      { name: 'Aether Warden', rarity: 'Mythic', art: 'https://images.unsplash.com/photo-1518709594023-6eab9bab7b23?w=300&h=420&fit=crop', power: 10200 },
      { name: 'Void Whisperer', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 8400 },
      { name: 'Realm Walker', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&h=420&fit=crop', power: 7100 },
    ],
    updates: [
      { date: 'Jul 12, 2026', title: 'Realms of Aetheria — Beta Phase 2', body: 'Added the merchant republic storyline with full voice acting. Economy rebalance and new crafting recipes.' },
      { date: 'Jul 1, 2026', title: 'Lore Drop — The Void', body: 'New lore video exploring the origins of the Void and its connection to the Aetheria pantheon. Watch on our community channel.' },
      { date: 'Jun 18, 2026', title: 'Community Q&A Recap', body: 'Answers to 50 community questions about Realms of Aetheria. Read the full transcript on our website.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '15' },
      { label: 'Active Projects', value: '2' },
      { label: 'Community Cards', value: '48' },
      { label: 'Dev Awards', value: '11' },
    ],
  },
  {
    id: 'quantum-games',
    name: 'Quantum Games',
    tagline: 'Sci-fi simulation specialists',
    description: 'Quantum Games builds deep simulation experiences set across the cosmos. Their proprietary physics engine models everything from orbital mechanics to ecosystem collapse, creating worlds that feel alive and scientifically grounded.',
    logo: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1920&h=600&fit=crop',
    accentColor: 'blue',
    founded: 2017,
    teamSize: 55,
    location: 'Berlin, Germany',
    gamesReleased: 6,
    followers: 87000,
    socials: { website: 'https://quantum.games', twitter: '@quantumgames' },
    releasedGames: [
      { title: 'Orbital Mechanics', genre: 'Space Sim', year: 2023, cover: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&h=500&fit=crop', description: 'A hard sci-fi space simulation with realistic Newtonian physics and orbital mechanics.' },
      { title: 'Ecosystem', genre: 'Simulation', year: 2020, cover: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=500&fit=crop', description: 'Model and evolve a complete ecosystem from microscopic organisms to apex predators.' },
      { title: 'Quantum Leap', genre: 'Puzzle', year: 2018, cover: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&h=500&fit=crop', description: 'A mind-bending puzzle game based on quantum mechanics and probability.' },
    ],
    inDevelopment: [
      {
        title: 'Stellar Diaspora',
        genre: 'Space Simulation',
        status: 'Alpha',
        progress: 55,
        cover: 'https://images.unsplash.com/photo-1446776877081-d282a0f896e2?w=400&h=500&fit=crop',
        description: 'A colony simulation where you manage a generation ship across centuries of interstellar travel. Every decision shapes the society that arrives.',
        releaseWindow: 'Q4 2027',
        features: ['Realistic orbital mechanics', 'Generational society simulation', 'Modding support'],
      },
      {
        title: 'Quantum Drift',
        genre: 'Sci-Fi Racing',
        status: 'Concept',
        progress: 8,
        cover: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=500&fit=crop',
        description: 'Anti-gravity racing through quantum slipstreams. Master the drift to bend space and time.',
        releaseWindow: '2028',
        features: ['Quantum slipstream tracks', '32 vehicles', 'Time-warp mechanics'],
      },
    ],
    customCards: [
      { name: 'Stellar Navigator', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=420&fit=crop', power: 7800 },
      { name: 'Quantum Rider', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 6200 },
    ],
    updates: [
      { date: 'Jul 5, 2026', title: 'Stellar Diaspora — Alpha 0.3', body: 'Generational system is now live. Watch your colonists age, reproduce, and develop unique cultural traits over simulated centuries.' },
      { date: 'Jun 20, 2026', title: 'Physics Engine Showcase', body: 'New video demonstrating our orbital mechanics engine. Every planet, moon, and asteroid follows real Newtonian physics.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '6' },
      { label: 'Active Projects', value: '2' },
      { label: 'Community Cards', value: '18' },
      { label: 'Dev Awards', value: '2' },
    ],
  },
  {
    id: 'iron-wolf',
    name: 'Iron Wolf',
    tagline: 'Hardcore survival and strategy games',
    description: 'Iron Wolf is a studio that doesn\'t hold your hand. Their games are punishing, deep, and rewarding. Known for their hardcore survival titles and complex strategy systems, they cater to players who want a real challenge.',
    logo: 'https://images.unsplash.com/photo-1558865869-c93f6f8482af?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1920&h=600&fit=crop',
    accentColor: 'red',
    founded: 2016,
    teamSize: 34,
    location: 'Stockholm, Sweden',
    gamesReleased: 9,
    followers: 156000,
    socials: { website: 'https://ironwolf.games', twitter: '@ironwolfdev' },
    releasedGames: [
      { title: 'Frostfall', genre: 'Survival', year: 2023, cover: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=400&h=500&fit=crop', description: 'The original brutal winter survival game. Hypothermia, hunger, and despair in a frozen wasteland.' },
      { title: 'Iron Kingdoms', genre: 'Grand Strategy', year: 2021, cover: 'https://images.unsplash.com/photo-1518182170546-0766ba6f0f2f?w=400&h=500&fit=crop', description: 'A grand strategy game spanning 500 years of alternate history. Manage dynasties and wage wars.' },
      { title: 'Wolfpack', genre: 'Tactical Shooter', year: 2019, cover: 'https://images.unsplash.com/photo-1509248961158-e54f69343a01?w=400&h=500&fit=crop', description: 'A hardcore tactical FPS with realistic ballistics and permadeath.' },
    ],
    inDevelopment: [
      {
        title: 'Frostfall: Last Hearth',
        genre: 'Survival',
        status: 'Beta',
        progress: 72,
        cover: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=400&h=500&fit=crop',
        description: 'A brutal winter survival game where hypothermia, hunger, and despair are your greatest enemies. Build, scavenge, and endure.',
        releaseWindow: 'Q1 2027',
        features: ['Realistic thermodynamics', 'Psychological survival', 'Co-op up to 4 players'],
      },
      {
        title: 'Iron Conquest',
        genre: 'Grand Strategy',
        status: 'Pre-Alpha',
        progress: 34,
        cover: 'https://images.unsplash.com/photo-1518182170546-0766ba6f0f2f?w=400&h=500&fit=crop',
        description: 'A grand strategy game spanning 500 years of alternate history. Manage dynasties, wage wars, and reshape the world.',
        releaseWindow: 'Q3 2027',
        features: ['500-year timeline', 'Dynamic dynasty system', 'Moddable everything'],
      },
    ],
    customCards: [
      { name: 'Frostborn Warrior', rarity: 'Mythic', art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=420&fit=crop', power: 9100 },
      { name: 'Iron Sentinel', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 7300 },
      { name: 'Winter Wolf', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&h=420&fit=crop', power: 6600 },
    ],
    updates: [
      { date: 'Jul 9, 2026', title: 'Frostfall — Beta Hard Mode', body: 'New "permadeath" mode is live. One life, no respawns. How long can you survive the endless winter?' },
      { date: 'Jun 25, 2026', title: 'Iron Conquest — Map Reveal', body: 'First look at the world map. 400+ provinces, 60+ starting nations, and a dynamic climate system.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '9' },
      { label: 'Active Projects', value: '2' },
      { label: 'Community Cards', value: '21' },
      { label: 'Dev Awards', value: '4' },
    ],
  },
  {
    id: 'pixel-forge',
    name: 'Pixel Forge',
    tagline: 'Retro-inspired modern classics',
    description: 'Pixel Forge believes that great gameplay never goes out of style. They craft retro-inspired games with modern sensibilities — tight controls, pixel-perfect art, and chiptune soundtracks that would feel at home in the golden age of arcade gaming.',
    logo: 'https://images.unsplash.com/photo-1614680376573-df3480f0c6ff?w=200&h=200&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1920&h=600&fit=crop',
    accentColor: 'green',
    founded: 2018,
    teamSize: 18,
    location: 'Austin, USA',
    gamesReleased: 11,
    followers: 93000,
    socials: { website: 'https://pixelforge.dev', twitter: '@pixelforge' },
    releasedGames: [
      { title: 'Pixel Dungeon', genre: 'Roguelike', year: 2023, cover: 'https://images.unsplash.com/photo-1551103782-8ab07d457281?w=400&h=500&fit=crop', description: 'A classic first-person dungeon crawler with procedural levels and permanent death.' },
      { title: 'Mega Pixel', genre: 'Platformer', year: 2021, cover: 'https://images.unsplash.com/photo-1547949003-9792a18a2601?w=400&h=500&fit=crop', description: 'A precision platformer with 50 hand-crafted levels and a beloved chiptune soundtrack.' },
      { title: 'Retro Racer', genre: 'Racing', year: 2020, cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=500&fit=crop', description: 'An arcade-style top-down racer with 24 tracks and local multiplayer.' },
      { title: 'Bit Quest', genre: 'Adventure', year: 2019, cover: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=400&h=500&fit=crop', description: 'A retro adventure RPG with a charming 8-bit art style and 30+ hours of content.' },
    ],
    inDevelopment: [
      {
        title: 'Bit Knight',
        genre: 'Action Platformer',
        status: 'Beta',
        progress: 89,
        cover: 'https://images.unsplash.com/photo-1551103782-8ab07d457281?w=400&h=500&fit=crop',
        description: 'A precision platformer with 100 hand-crafted levels. Every pixel matters as you dash, slash, and bounce through the bit kingdom.',
        releaseWindow: 'Q4 2026',
        features: ['100 hand-crafted levels', 'Speedrun mode', 'Chiptune soundtrack'],
      },
      {
        title: 'Dungeon Crawler DX',
        genre: 'Roguelike',
        status: 'Alpha',
        progress: 45,
        cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=500&fit=crop',
        description: 'A classic first-person dungeon crawler with procedural levels, permanent death, and a bestiary of 200+ creatures.',
        releaseWindow: 'Q2 2027',
        features: ['Procedural dungeons', '200+ monsters', 'Grid-based combat'],
      },
    ],
    customCards: [
      { name: 'Bit Knight', rarity: 'Legendary', art: 'https://images.unsplash.com/photo-1531259683007-016a7c1a34a5?w=300&h=420&fit=crop', power: 7500 },
      { name: 'Dungeon Master', rarity: 'Epic', art: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=300&h=420&fit=crop', power: 6800 },
      { name: 'Pixel Sprite', rarity: 'Rare', art: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=420&fit=crop', power: 5400 },
    ],
    updates: [
      { date: 'Jul 11, 2026', title: 'Bit Knight — Final Beta!', body: 'This is it! The last beta before launch. All 100 levels are playable. Send us your speedrun times!' },
      { date: 'Jul 2, 2026', title: 'Soundtrack Preview', body: 'Listen to 5 tracks from the official chiptune soundtrack, composed by legendary arcade composer Chip Maestro.' },
    ],
    milestones: [
      { label: 'Games Shipped', value: '11' },
      { label: 'Active Projects', value: '2' },
      { label: 'Community Cards', value: '27' },
      { label: 'Dev Awards', value: '5' },
    ],
  },
];