import {useRef,useState} from 'react';
import {useQueryClient} from '@tanstack/react-query';
import {ArrowRight,ArrowUpRight,Building2,Calendar,Check,Edit3,Gamepad2,ImagePlus,Plus,Send,Sparkles,X} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {GameCover} from '../redesign/StoreSections';
import {label} from '../redesign/discovery';
import {studioRequest,useStudioFeed} from './useStudioHub';

export const CATEGORIES={development:'Development',announcement:'Announcement',release:'New release',behind_scenes:'Behind the scenes'};
export function StudioLogo({studio}){
 const [failed,setFailed]=useState(false);
 return <span className="dev-logo">{studio.logo&&!failed?<img src={studio.logo} alt="" onError={()=>setFailed(true)}/>:studio.name.slice(0,2).toUpperCase()}</span>;
}
export function StudioCard({studio,onSelect}){
 return <button className="dev-studio-card" onClick={()=>onSelect(studio.key)}><div className="dev-studio-cover"><GameCover game={{cover_image:studio.cover}}/></div><div className="dev-studio-card-body"><StudioLogo studio={studio}/><h3>{studio.name}</h3><p>{studio.tagline||studio.genres.slice(0,3).map(label).join(' · ')||'Explore this studio’s catalog and updates.'}</p><div><span>{studio.games.length} store titles</span><span>{studio.projects.length} projects</span><ArrowRight size={13}/></div></div></button>;
}
export function ProjectCard({project,studio,onSelectStudio,onNavigateToGame,compact=false}){
 return <article className={'dev-project'+(compact?' dev-project-compact':'')}>
  <div className="dev-project-image"><GameCover game={{cover_image:project.image||studio.cover}}/><span>{label(project.status)}</span></div>
  <div className="dev-project-body"><button className="dev-byline" onClick={()=>onSelectStudio(studio.key)}>{studio.name}<ArrowUpRight size={11}/></button><h3>{project.title}</h3>{!compact&&<p>{project.description||'More project details will appear when the studio shares them.'}</p>}<div className="dev-project-meta">{project.genre&&<span>{label(project.genre)}</span>}{project.release_window&&<span>{project.release_window}</span>}</div><button className="dev-text-button" onClick={()=>project.game_id?onNavigateToGame(project.game_id):onSelectStudio(studio.key)}>{project.game_id?'Explore game':'Visit studio'}<ArrowRight size={13}/></button></div>
 </article>;
}
export function StudioFeed({studioKey='',studios,editableStudios,onSelectStudio,onNavigateToGame,onCompose}){
 const [category,setCategory]=useState('all'),feed=useStudioFeed(studioKey,category);
 const byKey=new Map(studios.map(studio=>[studio.key,studio]));
 return <section className="dev-feed" aria-label="Studio updates">
  <header className="dev-section-heading"><div><span className="dev-eyebrow">From the people making your games</span><h2>Studio updates</h2></div><select aria-label="Filter studio updates" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All updates</option>{Object.entries(CATEGORIES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></header>
  {feed.isLoading?<div role="status" className="dev-empty">Loading studio updates…</div>:feed.isError?<div className="dev-empty" role="alert"><p>Updates couldn’t load.</p><button onClick={()=>feed.refetch()}>Retry updates</button></div>:!feed.posts.length?<div className="dev-empty"><Edit3 size={23}/><h3>The next update starts here.</h3><p>Development diaries, announcements and release news will appear when studios publish them.</p>{studioKey&&editableStudios.includes(studioKey)&&<button className="dev-primary" onClick={()=>onCompose({studio_key:studioKey})}>Write an update<Plus size={13}/></button>}</div>:<div className="dev-posts">{feed.posts.map(post=>{
   const studio=byKey.get(post.studio_key)||{key:post.studio_key,name:post.studio_name||'Studio'};
   return <article className="dev-post" key={post.id}><header><button className="dev-post-author" onClick={()=>onSelectStudio(studio.key)}><StudioLogo studio={studio}/><span><strong>{studio.name}</strong><small>{new Date(post.published_at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})} · {CATEGORIES[post.category]||'Update'}</small></span></button>{editableStudios.includes(studio.key)&&<button className="dev-icon" aria-label={'Edit '+post.title} onClick={()=>onCompose(post)}><Edit3 size={14}/></button>}</header><h3>{post.title}</h3><p>{post.body}</p>{post.image_url&&<div className="dev-post-image"><GameCover game={{cover_image:post.image_url}}/></div>}<footer>{post.project_title&&<span><Gamepad2 size={13}/>{post.project_title}</span>}<button onClick={()=>post.game_id?onNavigateToGame(post.game_id):onSelectStudio(studio.key)}>{post.game_id?'Explore game':'Visit studio'}<ArrowUpRight size={13}/></button></footer></article>;
  })}</div>}
  {feed.hasNextPage&&<button className="dev-load-more" disabled={feed.isFetchingNextPage} onClick={()=>feed.fetchNextPage()}>{feed.isFetchingNextPage?'Loading…':'Load more updates'}</button>}
 </section>;
}
export function StudioComposer({initial,studios,onClose}){
 const client=useQueryClient(),[form,setForm]=useState({studio_key:initial.studio_key||studios[0]?.key||'',title:'',body:'',category:'development',project_title:'',game_id:'',image_url:'',...initial}),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(''),file=useRef(null);
 const studio=studios.find(s=>s.key===form.studio_key);
 const change=(key,value)=>setForm(f=>({...f,[key]:value}));
 const upload=async event=>{const image=event.target.files?.[0];if(!image)return;if(!['image/png','image/jpeg','image/webp'].includes(image.type)||image.size>8*1024*1024){setError('Choose a PNG, JPEG or WebP image under 8 MB.');return;}setUploading(true);setError('');try{const result=await base44.integrations.Core.UploadFile({file:image});if(!result.file_url)throw new Error('Image upload did not return a file.');change('image_url',result.file_url);}catch(e){setError(e.message||'Image upload failed.');}finally{setUploading(false);}};
 const submit=async event=>{event.preventDefault();if(busy||uploading)return;setBusy(true);setError('');try{await studioRequest('savePost',{...form,status:'published'});await client.invalidateQueries({queryKey:['studio-feed']});onClose();}catch(e){setError(e?.response?.data?.error||e.message||'Update could not be published.');}finally{setBusy(false);}};
 return <section className="dev-composer" aria-label="Write a studio update"><header><div><span className="dev-eyebrow">Your studio’s voice</span><h2>{initial.id?'Edit studio update':'Share what’s taking shape.'}</h2></div><button className="dev-icon" aria-label="Close update editor" onClick={onClose} disabled={busy}><X size={18}/></button></header><form onSubmit={submit}><div className="dev-composer-row"><label>Studio<select aria-label="Publishing studio" value={form.studio_key} disabled={!!initial.id||busy} onChange={e=>setForm(f=>({...f,studio_key:e.target.value,game_id:'',project_title:''}))}>{studios.map(s=><option key={s.key} value={s.key}>{s.name}</option>)}</select></label><label>Update type<select value={form.category} onChange={e=>change('category',e.target.value)}>{Object.entries(CATEGORIES).map(([key,value])=><option key={key} value={key}>{value}</option>)}</select></label></div><label>Title<input required minLength={3} maxLength={140} value={form.title} onChange={e=>change('title',e.target.value)} placeholder="What would you like players to know?"/></label><label>Update<textarea required minLength={10} maxLength={6000} rows={6} value={form.body} onChange={e=>change('body',e.target.value)} placeholder="Share a milestone, a behind-the-scenes look, or what’s coming next."/></label><div className="dev-composer-row"><label>Link a store game<select value={form.game_id} onChange={e=>change('game_id',e.target.value)}><option value="">No game link</option>{studio?.games.map(game=><option key={game.id} value={game.id}>{game.title}</option>)}</select></label><label>Project name (optional)<input maxLength={160} value={form.project_title} onChange={e=>change('project_title',e.target.value)}/></label></div>{form.image_url&&<div className="dev-composer-image"><img src={form.image_url} alt="Update image preview"/><button type="button" onClick={()=>change('image_url','')}>Remove image</button></div>}<input ref={file} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={upload}/>{error&&<p className="dev-error" role="alert">{error}</p>}<footer><button type="button" className="dev-text-button" disabled={uploading||busy} onClick={()=>file.current?.click()}><ImagePlus size={16}/>{uploading?'Uploading…':'Add image'}</button><span>Published updates are visible to players.</span><button type="submit" className="dev-primary" disabled={busy||uploading||!studio}><Send size={14}/>{busy?'Publishing…':initial.id?'Save update':'Publish update'}</button></footer></form></section>;
}
