import {useState} from 'react';
import {ArrowLeft,ArrowUpRight,Building2,Edit3,Gamepad2,Globe,MapPin} from 'lucide-react';
import {CompactGameCard} from '../redesign/CompactStoreSections';
import {GameCover} from '../redesign/StoreSections';
import {comingSoon} from '../redesign/discovery';
import {ProjectCard,StudioFeed,StudioLogo} from './StudioHubParts';
export default function StudioHubProfile({studio,studios,editableStudios,onBack,onSelectStudio,onNavigateToGame,onCompose}){
 const [tab,setTab]=useState('updates'),[page,setPage]=useState(0);
 const games=studio.games.filter(game=>!comingSoon(game));
 return <div className="dev-profile">
  <button className="dev-back" onClick={onBack}><ArrowLeft size={15}/>All studios</button>
  <div className="dev-profile-hero"><div className="dev-profile-art"><GameCover game={{banner_image:studio.cover}} wide/></div><div className="dev-profile-shade"/><div className="dev-profile-identity"><StudioLogo studio={studio}/><div><span className="dev-eyebrow">Studio profile</span><h1>{studio.name}</h1><p>{studio.tagline||'Explore the games and the people behind them.'}</p><span>{studio.games.length} games in the store · {studio.projects.length} current projects</span></div></div>{editableStudios.includes(studio.key)&&<button className="dev-primary" onClick={()=>onCompose({studio_key:studio.key})}><Edit3 size={14}/>Write update</button>}</div>
  <nav className="dev-profile-tabs" aria-label="Studio profile sections">{[['updates','Updates'],['projects','In development'],['games','Games'],['about','About']].map(([key,name])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>{setTab(key);setPage(0);}}>{name}</button>)}</nav>
  {tab==='updates'&&<div className="dev-profile-columns"><StudioFeed studioKey={studio.key} studios={studios} editableStudios={editableStudios} onSelectStudio={onSelectStudio} onNavigateToGame={onNavigateToGame} onCompose={onCompose}/><aside><div className="dev-section-heading"><h2>In the works</h2><span>{studio.projects.length}</span></div>{studio.projects.slice(0,3).map(project=><ProjectCard key={project.key} project={project} studio={studio} onSelectStudio={()=>setTab('projects')} onNavigateToGame={onNavigateToGame} compact/>)}{!studio.projects.length&&<p className="dev-muted">New projects will appear when added to this studio’s profile.</p>}<button className="dev-text-button" onClick={()=>setTab('about')}>About {studio.name}<ArrowUpRight size={13}/></button></aside></div>}
  {tab==='projects'&&<><header className="dev-section-heading"><div><h2>What’s taking shape</h2><p>Current and upcoming projects listed in the studio profile.</p></div></header><div className="dev-project-grid">{studio.projects.map(project=><ProjectCard key={project.key} project={project} studio={studio} onSelectStudio={()=>setTab('about')} onNavigateToGame={onNavigateToGame}/>)}</div>{!studio.projects.length&&<div className="dev-empty">No upcoming projects have been listed yet.</div>}</>}
  {tab==='games'&&<><header className="dev-section-heading"><div><h2>Games from {studio.name}</h2><p>{games.length} released titles in this store</p></div></header><div className="dev-games-grid">{games.slice(page*15,(page+1)*15).map(game=><CompactGameCard key={game.id} game={game} onSelect={onNavigateToGame}/>)}</div>{!games.length&&<div className="dev-empty"><Gamepad2/><p>This studio’s released games will appear when linked to the store.</p></div>}{games.length>15&&<div className="dev-pagination"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>{page+1} / {Math.ceil(games.length/15)}</span><button disabled={(page+1)*15>=games.length} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</>}
  {tab==='about'&&<section className="dev-about"><div><span className="dev-eyebrow">Behind the games</span><h2>{studio.name}</h2><p>{studio.description||'This studio has not added a description yet.'}</p>{studio.website&&<a className="dev-text-button" href={studio.website} target="_blank" rel="noopener noreferrer"><Globe size={15}/>Studio website<ArrowUpRight size={13}/></a>}</div><dl>{studio.location&&<div><dt>Location</dt><dd>{studio.location}</dd></div>}{studio.founded&&<div><dt>Founded</dt><dd>{studio.founded}</dd></div>}<div><dt>Store titles</dt><dd>{studio.games.length}</dd></div><div><dt>Current projects</dt><dd>{studio.projects.length}</dd></div></dl>{studio.notable.length>0&&<div className="dev-known-for"><h3>Also known for</h3><p>Titles listed in the studio profile; availability in this store may vary.</p><div>{studio.notable.map(game=><span key={game.title}>{game.title}{game.year?' · '+game.year:''}</span>)}</div></div>}</section>}
 </div>;
}
