import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Compass, MicOff, Swords, Trophy } from 'lucide-react';
import { Artwork } from '../../hub/DirectoryCards';
import { formatEditionDate } from './auraDailyModel';

export default function AuraDailyBriefing({ edition, loading, onRead, onBrowse, image }) {
  const [lead, ...headlines] = edition.updates;
  return <>
    <div className="aura-briefing-layout">
      {lead ? <button type="button" className="aura-briefing-lead" onClick={() => onRead(lead)} aria-label={`Read ${lead.title}`}><Artwork key={lead.image} src={lead.image} /><div className="aura-daily-vignette" /><div className="aura-briefing-lead-copy"><span className="console-eyebrow">{lead.label}</span><h3>{lead.title}</h3><p>{lead.description}</p><span className="aura-daily-meta">{formatEditionDate(lead.publishedAt)}<span>Read the story<ArrowRight size={14} /></span></span></div></button> : <div className="aura-briefing-lead is-guide"><Artwork key={image} src={image} /><div className="aura-daily-vignette" /><div className="aura-briefing-lead-copy"><span className="console-eyebrow">The Aura watch guide</span><h3>A new perspective.<br />One stream away.</h3><p>Meet a creator, join a quieter community, or follow someone on their next achievement hunt.</p><Link className="console-text-button" to="/discover">Meet your next favorite<ArrowRight size={15} /></Link></div></div>}
      <div className="aura-briefing-headlines"><div className="aura-daily-subheading"><BookOpen size={14} /><h3>From Atom x Eve</h3></div>{headlines.map((story) => <button type="button" key={story.id} onClick={() => onRead(story)}><span className="aura-daily-label">{story.label} · {formatEditionDate(story.publishedAt)}</span><strong>{story.title}</strong><p>{story.description}</p><ArrowRight size={14} /></button>)}{!headlines.length && <p className="aura-daily-quiet">{loading ? 'Loading the latest updates…' : lead ? 'You’re caught up with the latest published update.' : 'Published announcements and platform updates will appear here.'}</p>}<div className="aura-briefing-note"><span className="console-eyebrow">Make it your kind of live</span><p>Use stream styles to find the pace, personality, and community you want to spend time with.</p><Link to="/discover" className="console-text-button">Explore stream styles<ArrowRight size={13} /></Link></div></div>
    </div>
    <div className="aura-community-dispatch"><div className="aura-daily-subheading"><Trophy size={14} /><h3>Community dispatch</h3><span>Guides, tips & achievement stories</span></div>{edition.posts.length > 0 ? <div className="aura-community-stories">{edition.posts.map((story) => <button type="button" key={story.id} onClick={() => onRead(story)}><span className="aura-daily-label">{story.label}</span><h4>{story.title}</h4><p>{story.description || formatEditionDate(story.publishedAt)}</p><ArrowRight size={14} /></button>)}</div> : <div className="aura-watch-guides"><button type="button" onClick={() => onBrowse({ style: 'competitive' })}><Swords size={19} /><span><strong>Follow the climb</strong><small>Ranked matches and competitive sessions.</small></span><ArrowRight size={14} /></button><button type="button" onClick={() => onBrowse({ style: 'no commentary' })}><MicOff size={19} /><span><strong>Let the game speak</strong><small>Find a stream without commentary.</small></span><ArrowRight size={14} /></button><Link to="/discover"><Compass size={19} /><span><strong>Take a different route</strong><small>New creators and smaller communities.</small></span><ArrowRight size={14} /></Link></div>}</div>
  </>;
}
