import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, Clock3, Play, Radio } from 'lucide-react';
import { Artwork } from '../../hub/DirectoryCards';
import { formatCount } from '../../hub/discoveryModel';
import { formatEditionDate } from './auraDailyModel';

export default function AuraUpNext({ edition, loading, onRead, onLive, onGames }) {
  return <>
    <div className="aura-next-layout"><section className="aura-schedule-list" aria-label="Streams scheduled in the next seven days"><div className="aura-daily-subheading"><CalendarDays size={15} /><h3>On the horizon</h3><span>Next 7 days</span></div>{edition.schedules.length ? edition.schedules.map((schedule) => <Link to={schedule.isSample ? '#' : schedule.href} onClick={schedule.isSample ? (event) => { event.preventDefault(); onRead(schedule); } : undefined} key={schedule.id} className="aura-scheduled-stream"><time dateTime={new Date(schedule.startsAt).toISOString()}><strong>{new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(schedule.startsAt)}</strong><small>{new Intl.DateTimeFormat(undefined, { weekday: 'short', month: 'short', day: 'numeric' }).format(schedule.startsAt)}</small></time><Artwork key={schedule.avatar} src={schedule.avatar} avatar className="console-avatar" /><span><strong>{schedule.title}</strong><small>{schedule.isSample ? 'Sample · ' : ''}{schedule.creator}{schedule.game ? ` · ${schedule.game}` : ''}</small></span><ArrowRight size={14} /></Link>) : <div className="aura-schedule-empty"><Clock3 size={24} /><h4>{loading ? 'Checking what’s coming up…' : 'Room for the next live moment.'}</h4><p>{loading ? 'Loading creator schedules.' : 'Streams scheduled for the next seven days will appear here as creators share their plans.'}</p><button type="button" className="console-text-button" onClick={onLive}>See who’s live now<ArrowRight size={14} /></button></div>}<p className="aura-daily-quiet">Times are shown in your local time zone.</p></section><aside className="aura-next-invitation"><span className="console-eyebrow">While you’re here</span><h3>There’s always<br />another world.</h3><p>Go deeper into a game you love, or start with something you haven’t watched before.</p><button type="button" className="console-text-button" onClick={onGames}>Explore game worlds<ArrowRight size={15} /></button><div><Radio size={15} /><span>Aura keeps the live directory updated as channels come online.</span></div></aside></div>
    <section className="aura-replays" aria-label="Public recordings and uploads"><div className="aura-daily-subheading"><Play size={14} /><h3>In case you missed it</h3><span>Public recordings & uploads</span></div>{edition.videos.length ? <div className="aura-replay-grid">{edition.videos.map((video) => <button type="button" key={video.id} onClick={() => onRead(video)} aria-label={`Play recording: ${video.title}`}><div className="aura-replay-art"><Artwork key={video.image} src={video.image} /><div className="aura-daily-vignette" /><Play size={24} />{video.duration && <span>{video.duration}</span>}</div><span className="aura-daily-label">{video.label}</span><h4>{video.title}</h4><p>{formatCount(video.views)} views{video.publishedAt ? ` · ${formatEditionDate(video.publishedAt)}` : ''}</p></button>)}</div> : <div className="aura-replay-empty"><p>{loading ? 'Loading recent recordings…' : 'Public recordings and uploads will appear here when creators share them.'}</p><button type="button" className="console-text-button" onClick={onLive}>Catch a live moment instead<ArrowRight size={14} /></button></div>}</section>
  </>;
}