// ─── Skill Drop, Evolution, and Upgrade System ─────────────────────────────

export const RARITIES = [
  { id: 'common',    label: 'Common',    color: '#9ca3af', glow: 'rgba(156,163,175,0.3)' },
  { id: 'rare',      label: 'Rare',      color: '#60a5fa', glow: 'rgba(96,165,250,0.3)' },
  { id: 'epic',      label: 'Epic',      color: '#a78bfa', glow: 'rgba(167,139,250,0.35)' },
  { id: 'legendary', label: 'Legendary', color: '#f59e0b', glow: 'rgba(245,158,11,0.4)' },
  { id: 'mythic',    label: 'Mythic',    color: '#f43f5e', glow: 'rgba(244,63,94,0.45)' },
  { id: 'divine',    label: 'Divine',    color: '#e879f9', glow: 'rgba(232,121,249,0.5)' },
];

export const EVOLUTION_RANKS = [
  { id: 'base',     label: 'Base',     tier: 0, color: '#9ca3af' },
  { id: 'master',   label: 'Master',   tier: 1, color: '#60a5fa' },
  { id: 'demigod',  label: 'Demigod',  tier: 2, color: '#a78bfa' },
  { id: 'god',      label: 'God',      tier: 3, color: '#f59e0b' },
  { id: 'chosen',   label: 'Chosen',   tier: 4, color: '#e879f9' },
];

export const UPGRADE_MATERIALS = [
  { id: 'soul_fragment',  name: 'Soul Fragment',  icon: '💠', color: '#60a5fa' },
  { id: 'divine_essence', name: 'Divine Essence', icon: '✨', color: '#e879f9' },
  { id: 'void_crystal',   name: 'Void Crystal',   icon: '🔮', color: '#a78bfa' },
  { id: 'ancient_relic',  name: 'Ancient Relic',  icon: '🏺', color: '#f59e0b' },
  { id: 'aura_shard',     name: 'Aura Shard',     icon: '🌟', color: '#fcd34d' },
];

// Mock player material inventory
export const PLAYER_MATERIALS = {
  soul_fragment:  12,
  divine_essence: 3,
  void_crystal:   7,
  ancient_relic:  1,
  aura_shard:     20,
};

export const DROP_SOURCES = {
  world_boss:        { label: 'World Boss',        icon: '👹', color: '#ef4444' },
  elite_enemy:       { label: 'Elite Enemy',       icon: '⚔️', color: '#f97316' },
  clan_raid:         { label: 'Clan Raid',          icon: '🏰', color: '#3b82f6' },
  dimensional_event: { label: 'Dimensional Event',  icon: '🌀', color: '#a78bfa' },
  hidden_dungeon:    { label: 'Hidden Dungeon',     icon: '🗝️', color: '#10b981' },
  legendary_encounter: { label: 'Legendary Encounter', icon: '⭐', color: '#f59e0b' },
};

export const SKILLS_DATABASE = [
  // ── PASSIVE SKILLS (special visuals) ─────────────────────────────────────
  {
    id: 'repulsion',
    name: 'Repulsion',
    evolvedName: "God's Repulsion",
    path: 'defense',
    rarity: 'legendary',
    icon: '⚡',
    description: 'Creates an electrified ozone-like barrier that orbits the player, reflecting projectiles. At max level evolves into God\'s Repulsion — a crackling lightning sphere that repels all incoming forces.',
    type: 'Reflect Shield',
    drop_source: 'dimensional_event',
    evolution_rank: 'base',
    upgrade_cost: { void_crystal: 6, divine_essence: 3 },
    owned: true,
    equipped: false,
    passive_aura: 'repulsion',
  },
  {
    id: 'barrier_aura',
    name: 'Barrier',
    path: 'defense',
    rarity: 'epic',
    icon: '🛡️',
    description: 'Wraps the player in a luminous energy aura that glows around the body outline, absorbing a percentage of incoming damage. Visual signifier that a guardian shield is active.',
    type: 'Body Shield',
    drop_source: 'world_boss',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, divine_essence: 2 },
    owned: true,
    equipped: false,
    passive_aura: 'barrier',
  },
  {
    id: 'heavens_destruction',
    name: "Heaven's Destruction",
    path: 'defense',
    rarity: 'mythic',
    icon: '🌑',
    description: 'Channels dark divine lightning in a tilted orbital ring around the player. Has a chance to negate critical strikes. The angled trajectory prevents overlap with other aura effects.',
    type: 'Crit Negate',
    drop_source: 'legendary_encounter',
    evolution_rank: 'master',
    upgrade_cost: { ancient_relic: 3, divine_essence: 5, void_crystal: 4 },
    owned: true,
    equipped: false,
    passive_aura: 'heavens_destruction',
  },
  // ── NEW NON-TARGETED ACTIVE / BUFF SKILLS ────────────────────────────────
  {
    id: 'aegis_shield',
    name: 'Aegis Shield',
    path: 'defense',
    rarity: 'epic',
    icon: '🛡️',
    description: 'Instantly conjures a protective shield equal to 15% of your max HP. Self-cast — does not require a target.',
    type: 'Self Shield',
    shield_pct: 0.15,
    requires_target: false,
    drop_source: 'world_boss',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, divine_essence: 2 },
    owned: true,
    equipped: false,
  },
  {
    id: 'decisive_blow',
    name: 'Decisive Blow',
    path: 'damage',
    rarity: 'epic',
    icon: '🎯',
    description: 'Sharpens your focus, increasing critical strike damage. Self-buff — no target required.',
    type: 'Crit Damage Buff',
    crit_damage_bonus_pct: 0.25,
    requires_target: false,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 4, void_crystal: 2 },
    owned: true,
    equipped: false,
  },
  {
    id: 'focus',
    name: 'Focus',
    path: 'damage',
    rarity: 'rare',
    icon: '🧠',
    description: 'Enter a state of perfect concentration — your next 5 hits deal increased damage. Self-buff, no target required.',
    type: 'Damage Buff (5 hits)',
    damage_bonus_pct: 0.30,
    hits: 5,
    requires_target: false,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 3 },
    owned: true,
    equipped: false,
  },
  {
    id: 'gods_deflection',
    name: "God's Deflection",
    path: 'defense',
    rarity: 'legendary',
    icon: '✨',
    description: 'A divine ward grants a chance to reflect 100% of incoming damage back at your attacker. Starts at 3% chance at level 1. Self-buff, no target required.',
    type: 'Reflect Chance',
    reflect_pct: 1.0,
    reflect_chance_pct: 0.03,
    requires_target: false,
    drop_source: 'dimensional_event',
    evolution_rank: 'base',
    upgrade_cost: { void_crystal: 5, divine_essence: 2 },
    owned: true,
    equipped: false,
  },
  {
    id: 'haste',
    name: 'Haste',
    evolvedName: 'Fortified Speed',
    path: 'ranged',
    rarity: 'epic',
    icon: '⚡',
    description: 'Quickens your ranged attacks, increasing fire rate. Starts at 1% at level 1, scaling up to 20% at max level. Self-buff, no target required. Requires a ranged weapon to activate.',
    type: 'Attack Speed Buff',
    attack_speed_pct_min: 0.01,
    attack_speed_pct_max: 0.20,
    requires_target: false,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 4, void_crystal: 2 },
    owned: true,
    equipped: false,
  },
  // ── WEAPON-CLASS NATIVE PASSIVES (always-on while that class is equipped) ─
  {
    id: 'brutal_force',
    name: 'Brutal Force',
    path: 'damage',
    rarity: 'legendary',
    icon: '⚔️',
    description: 'Native passive of all damage-class weapons. Scales up to +35% damage and a 2% Lethal Blow (instant-kill) chance at max level (20). Always active while a damage weapon is equipped.',
    type: 'Weapon-Class Passive',
    weapon_class_passive: true,
    max_level: 20,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 6, void_crystal: 3 },
    owned: true,
    equipped: false,
  },
  {
    id: 'swift_marksman',
    name: 'Swift Marksman',
    path: 'ranged',
    rarity: 'legendary',
    icon: '🏹',
    description: 'Native passive of all ranged-class weapons. At max level (25): +25% movement, +15% hit chance, +10% damage and +5% critical strike chance. Always active while a ranged weapon is equipped.',
    type: 'Weapon-Class Passive',
    weapon_class_passive: true,
    max_level: 25,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 6, aura_shard: 3 },
    owned: true,
    equipped: false,
  },
  {
    id: 'iron_stance',
    name: 'Iron Stance',
    path: 'defense',
    rarity: 'legendary',
    icon: '🛡️',
    description: 'Native passive of all defense-class weapons. At max level (20): +40% defense, +20% damage, +7% dodge and +7% guard (chance for enemies to miss). Always active while a defense weapon is equipped.',
    type: 'Weapon-Class Passive',
    weapon_class_passive: true,
    max_level: 20,
    drop_source: 'clan_raid',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 6, divine_essence: 2 },
    owned: true,
    equipped: false,
  },
  // ── DAMAGE PATH ──────────────────────────────────────────────────────────
  {
    id: 'berserker_slash',
    name: 'Berserker Slash',
    path: 'damage',
    rarity: 'epic',
    icon: '⚔️',
    description: 'A savage overhead strike that shreds enemy defenses.',
    damage_pct: 1.45,
    type: 'Single Burst',
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, void_crystal: 2 },
    owned: true,
    equipped: false,
  },
  // ── DEFENSE PATH ──────────────────────────────────────────────────────────
  {
    id: 'iron_fortress',
    name: 'Iron Fortress',
    path: 'defense',
    rarity: 'rare',
    icon: '🏰',
    description: 'Raises an iron bulwark, dramatically reducing incoming damage.',
    type: 'Block Stance',
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 4 },
    owned: true,
    equipped: false,
  },
  {
    id: 'counter_pulse',
    name: 'Counter Pulse',
    path: 'defense',
    rarity: 'epic',
    icon: '🔄',
    description: 'Emits a pulse on successful block, staggering nearby attackers.',
    type: 'Counter AoE',
    drop_source: 'clan_raid',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, void_crystal: 3 },
    owned: true,
    equipped: false,
  },
  {
    id: 'guardian_wall',
    name: 'Guardian Wall',
    path: 'defense',
    rarity: 'legendary',
    icon: '🛡️',
    description: 'Projects an energy wall that blocks projectiles for the party.',
    type: 'Party Shield',
    drop_source: 'world_boss',
    evolution_rank: 'master',
    upgrade_cost: { divine_essence: 4, aura_shard: 6 },
    owned: false,
    equipped: false,
  },
  {
    id: 'reflective_guard',
    name: 'Reflective Guard',
    path: 'defense',
    rarity: 'mythic',
    icon: '🪞',
    description: 'A perfect mirror shield that reflects 100% of damage on activation.',
    type: 'Reflect Skill',
    drop_source: 'dimensional_event',
    evolution_rank: 'demigod',
    upgrade_cost: { void_crystal: 8, ancient_relic: 2, divine_essence: 3 },
    owned: false,
    equipped: false,
  },
  {
    id: 'shield_slash',
    name: 'Shield Slash',
    path: 'defense',
    rarity: 'rare',
    icon: '⚔️',
    description: 'A single decisive slash with your shield-bound blade. Deals 80% weapon damage at level 1, scaling up to 100% at max level.',
    type: 'Single Hit',
    damage_pct_min: 0.80,
    damage_pct_max: 1.00,
    requires_target: false,
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 4 },
    owned: true,
    equipped: false,
  },
  {
    id: 'guardian_triple_strike',
    name: 'Guardian Triple Strike',
    path: 'defense',
    rarity: 'epic',
    icon: '⚔️',
    description: 'Unleashes three rapid shield-strikes on the nearest enemy. Each hit deals 90% weapon damage at level 1, scaling up to 110% at max level.',
    type: 'Three Hit',
    damage_pct_min: 0.90,
    damage_pct_max: 1.10,
    hits: 3,
    requires_target: false,
    drop_source: 'clan_raid',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, void_crystal: 2 },
    owned: true,
    equipped: false,
  },
  // ── RANGED PATH ────────────────────────────────────────────────────────────
  {
    id: 'barrage_volley',
    name: 'Barrage Volley',
    path: 'ranged',
    rarity: 'common',
    icon: '🌪️',
    description: 'Fires 5 rapid shots in quick succession.',
    type: 'Multi-Hit Ranged',
    drop_source: 'elite_enemy',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 2 },
    owned: true,
    equipped: true,
  },
  {
    id: 'phantom_shot',
    name: 'Phantom Shot',
    path: 'ranged',
    rarity: 'epic',
    icon: '👻',
    description: 'A spectral arrow that passes through obstacles and enemies.',
    damage_pct: 1.35,
    type: 'Pierce Shot',
    drop_source: 'hidden_dungeon',
    evolution_rank: 'base',
    upgrade_cost: { soul_fragment: 5, aura_shard: 3 },
    owned: true,
    equipped: false,
  },
  {
    id: 'storm_rounds',
    name: 'Storm Rounds',
    path: 'ranged',
    rarity: 'legendary',
    icon: '⛈️',
    description: 'Channels lightning into shots, creating chain lightning on hit.',
    damage_pct: 1.60,
    type: 'Chain Lightning',
    drop_source: 'world_boss',
    evolution_rank: 'master',
    upgrade_cost: { void_crystal: 6, divine_essence: 3 },
    owned: false,
    equipped: false,
  },
  {
    id: 'piercing_rain',
    name: 'Piercing Rain',
    path: 'ranged',
    rarity: 'divine',
    icon: '🌧️',
    description: 'Calls down a rain of divine arrows that pierce through all targets.',
    damage_pct: 2.40,
    type: 'Ultimate Rain',
    drop_source: 'legendary_encounter',
    evolution_rank: 'god',
    upgrade_cost: { ancient_relic: 4, divine_essence: 8, aura_shard: 10 },
    owned: false,
    equipped: false,
  },
];