// ─── Weapon Path & Buff Skill System ───────────────────────────────────────
// Three weapon paths (Damage, Defense, Ranged) + 6 universal buff skills.
// Each path has: passive, single-hit skill, and multi-hit combo skill.

export const UNIVERSAL_BUFFS = [
  {
    id: 'berserker_buff',
    name: 'Berserker Buff',
    type: 'Universal Damage Buff',
    icon: '🔥',
    color: '#f97316',
    description: 'Increases all damage dealt by 30%.',
    details: 'Duration and cooldown scalable through upgrades.',
    effect: { damage_bonus: 0.30 },
  },
  {
    id: 'rapid_assault',
    name: 'Rapid Assault',
    type: 'Universal Attack Speed Buff',
    icon: '⚡',
    color: '#facc15',
    description: 'Increases attack speed significantly.',
    details: 'Shared across all weapon types.',
    effect: { attack_speed_bonus: 'high' },
  },
  {
    id: 'forward_shield',
    name: 'Forward Shield',
    type: 'Universal Defensive Shield',
    icon: '🛡️',
    color: '#38bdf8',
    description: 'Grants a temporary shield equal to 15% of Max HP.',
    details: 'At 10,000 HP → 1,500 temporary shield HP.',
    effect: { shield_pct_of_max_hp: 0.15 },
  },
  {
    id: 'reflect_barrier',
    name: 'Reflect Barrier',
    type: 'Universal Reflection Buff',
    icon: '🔄',
    color: '#a78bfa',
    description: 'Reflects a percentage of incoming damage back to attackers.',
    details: 'Reflection amount scales with upgrades.',
    effect: { reflect_damage: true },
  },
  {
    id: 'critical_resistance',
    name: 'Critical Resistance',
    type: 'Universal Defensive Utility Buff',
    icon: '🧲',
    color: '#4ade80',
    description: 'Reduces chance of receiving critical hits.',
    details: 'Also provides partial hit resistance and stagger immunity.',
    effect: { reduce_enemy_crit: true, hit_resistance: true },
  },
  {
    id: 'overdrive_strike',
    name: 'Overdrive Strike',
    type: 'Universal Burst Buff',
    icon: '💥',
    color: '#fb923c',
    description: 'Increases damage of the next 5 attacks by 100%.',
    details: 'Activate for a devastating burst window.',
    effect: { next_attacks: 5, damage_multiplier: 2.0 },
  },
];

export const WEAPON_PATHS = [
  {
    id: 'damage',
    name: 'Damage Path',
    subtitle: 'Greatsword / Heavy Weapon',
    focus: 'High offensive burst damage — slow but powerful attacks',
    icon: '⚔️',
    color: '#ef4444',
    gradient: 'from-red-900/60 to-red-800/20',
    borderColor: 'border-red-500/40',
    glowColor: 'rgba(239,68,68,0.25)',
    passive: {
      name: 'Brutal Force',
      type: 'Weapon-Specific Passive',
      description: 'Increases total damage dealt by 25%.',
      icon: '📈',
      effect: { damage_bonus: 0.25 },
    },
    skills: [
      {
        id: 'heavy_impact',
        name: 'Heavy Impact',
        type: 'Single Hit Burst Skill',
        icon: '🪨',
        description: 'Deals 130% weapon damage in a single devastating strike.',
        hits: 1,
        damage_pct: 1.30,
        pattern: ['130% weapon damage'],
      },
      {
        id: 'triple_cleave',
        name: 'Triple Cleave',
        type: 'Multi-Hit Combo Skill',
        icon: '🌀',
        description: 'Performs 3 consecutive heavy strikes over 1 second.',
        hits: 3,
        pattern: ['Hit 1', '⏱ 0.5s', 'Hit 2', '⏱ 0.5s', 'Hit 3'],
      },
    ],
  },
  {
    id: 'defense',
    name: 'Defense Path',
    subtitle: 'Dual Blades',
    focus: 'Defensive combat, counter-attacks, sustained melee pressure',
    icon: '🗡️',
    color: '#3b82f6',
    gradient: 'from-blue-900/60 to-blue-800/20',
    borderColor: 'border-blue-500/40',
    glowColor: 'rgba(59,130,246,0.25)',
    passive: {
      name: 'Iron Stance',
      type: 'Weapon-Specific Passive',
      description: 'Increases defense by 50%.',
      icon: '🏰',
      effect: { defense_bonus: 0.50 },
    },
    skills: [
      {
        id: 'counter_slash',
        name: 'Counter Slash',
        type: 'Defensive Counter Skill',
        icon: '↩️',
        description: 'Deals 120% of native weapon damage as a counter strike.',
        hits: 1,
        damage_pct: 1.20,
        pattern: ['120% weapon damage on counter'],
      },
      {
        id: 'twin_fang_combo',
        name: 'Twin Fang Combo',
        type: 'Multi-Hit Combo Skill',
        icon: '⚡',
        description: 'First 2 hits occur simultaneously, final hit after 0.5s delay.',
        hits: 3,
        pattern: ['Hit 1 + Hit 2 (simultaneous)', '⏱ 0.3s', 'Final Hit', '⏱ 0.5s delay'],
      },
    ],
  },
  {
    id: 'ranged',
    name: 'Ranged Path',
    subtitle: 'Bow / Firearm / Energy Weapon',
    focus: 'Mobility, evasion, and sustained ranged pressure',
    icon: '🏹',
    color: '#10b981',
    gradient: 'from-emerald-900/60 to-emerald-800/20',
    borderColor: 'border-emerald-500/40',
    glowColor: 'rgba(16,185,129,0.25)',
    passive: {
      name: 'Swift Marksman',
      type: 'Weapon-Specific Passive',
      description: 'Increases movement speed by 35% and reduces chance of being hit by 20%.',
      icon: '💨',
      effect: { move_speed_bonus: 0.35, dodge_chance: 0.20 },
    },
    skills: [
      {
        id: 'precision_shot',
        name: 'Precision Shot',
        type: 'Single Target Burst Skill',
        icon: '🎯',
        description: 'Deals 125% weapon damage with pinpoint accuracy.',
        hits: 1,
        damage_pct: 1.25,
        pattern: ['125% weapon damage (single target)'],
      },
      {
        id: 'barrage_volley',
        name: 'Barrage Volley',
        type: 'Multi-Hit Ranged Skill',
        icon: '🌪️',
        description: 'Fires 5 consecutive ranged hits, each 0.4 seconds apart.',
        hits: 5,
        pattern: ['Hit 1', '⏱ 0.4s', 'Hit 2', '⏱ 0.4s', 'Hit 3', '⏱ 0.4s', 'Hit 4', '⏱ 0.4s', 'Hit 5'],
      },
    ],
  },
];