import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {build} from 'esbuild';
import {JSDOM} from 'jsdom';
const dir=path.resolve('node_modules/.cache/luna-check');fs.mkdirSync(dir,{recursive:true});
await build({entryPoints:['src/components/onboarding/GenesisFaceScan.jsx'],outfile:dir+'/camera.mjs',bundle:true,format:'esm',platform:'node',packages:'external',jsx:'automatic',plugins:[{name:'face-inference-stub',setup(b){b.onResolve({filter:/selfieFit$/},()=>({path:'stub',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:"export const drawSelfie=x=>x;export async function fitSelfie(){globalThis.__fitCalls++;return {face_shape:{jaw_width:.4},face_fit_source:'selfie'};}",loader:'js'}));}}]});
const dom=new JSDOM('<div id="app"></div>',{url:'https://avatar.example'});
Object.assign(globalThis,{window:dom.window,document:dom.window.document,navigator:dom.window.navigator,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true,__fitCalls:0});
dom.window.HTMLMediaElement.prototype.play=async()=>{};
let stops=0;const media={getTracks:()=>[{stop(){stops++;}}]};
Object.defineProperty(navigator,'mediaDevices',{configurable:true,value:{getUserMedia:async()=>media}});
const React=await import('react'),{createRoot}=await import('react-dom/client'),{default:Camera}=await import('file://'+dir+'/camera.mjs');
const {act}=React;let config={},root;
const mount=async()=>{root=createRoot(document.getElementById('app'));await act(async()=>root.render(React.createElement(Camera,{config,setConfig:update=>{config=update(config);}})));};
const click=async label=>{const button=[...document.querySelectorAll('button')].find(b=>b.textContent===label);assert(button,'Button '+label);await act(async()=>button.click());};
await mount();await click('Enable camera');assert(document.querySelector('video').srcObject===media);
const capture=[...document.querySelectorAll('button')].find(b=>b.textContent==='Use this photo');assert(capture.disabled,'Capture waits for video readiness');
await act(async()=>document.querySelector('video').dispatchEvent(new window.Event('loadeddata')));
await click('Use this photo');assert.equal(__fitCalls,1);assert.equal(config.face_shape.jaw_width,.4);assert.equal(stops,1);assert(!document.querySelector('video'));await act(async()=>root.unmount());
navigator.mediaDevices.getUserMedia=async()=>{const e=Error('blocked');e.name='NotAllowedError';throw e;};
await mount();await click('Enable camera');assert(document.querySelector('[role=alert]').textContent.includes('permission denied'));assert(![...document.querySelectorAll('button')].find(b=>b.textContent==='Upload photo').disabled);await act(async()=>root.unmount());
let resolve; navigator.mediaDevices.getUserMedia=()=>new Promise(r=>{resolve=r;});await mount();await click('Enable camera');await act(async()=>root.unmount());await act(async()=>{resolve(media);await Promise.resolve();});assert.equal(stops,2,'Late permission grant must release its camera stream');
navigator.mediaDevices.getUserMedia=async()=>media;await mount();const input=document.querySelector('input[type=file]');Object.defineProperty(input,'files',{configurable:true,value:[new window.File(['bad'],'bad.txt',{type:'text/plain'})]});await act(async()=>input.dispatchEvent(new window.Event('change',{bubbles:true})));assert(document.querySelector('[role=alert]').textContent.includes('JPG'));
let revoked=0;globalThis.URL.createObjectURL=()=> 'blob:unit-photo';globalThis.URL.revokeObjectURL=()=>{revoked++;};globalThis.Image=class{async decode(){}};
Object.defineProperty(input,'files',{configurable:true,value:[new window.File(['photo'],'face.png',{type:'image/png'})]});await act(async()=>{input.dispatchEvent(new window.Event('change',{bubbles:true}));await Promise.resolve();await Promise.resolve();});assert.equal(__fitCalls,2);assert.equal(revoked,1);await act(async()=>root.unmount());
console.log(JSON.stringify({passed:true,camera:'grant, readiness, capture, denial, late grant cleanup',upload:'type validation, successful fit, blob cleanup',inference:'mocked; no camera image or ML inference executed'}));
