import {useEffect,useRef,useState} from 'react';
import {fitSelfie,drawSelfie} from './selfieFit';
export default function GenesisFaceScan({config,setConfig}){
 const video=useRef(null),stream=useRef(null),alive=useRef(true),version=useRef(0),file=useRef(null);
 const [camera,setCamera]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const stop=()=>{version.current++;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setCamera(false);setReady(false);};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;version.current++;stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 const start=async()=>{const request=++version.current;setError('');try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera needs HTTPS and browser support. You can upload a photo instead.');const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:1280}},audio:false});if(!alive.current||request!==version.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;setCamera(true);}catch(e){if(alive.current)setError(e.name==='NotAllowedError'?'Camera permission denied. Allow it in browser settings or upload a photo.':e.message);}};
 useEffect(()=>{if(camera&&video.current){video.current.srcObject=stream.current;video.current.play().catch(()=>setError('Camera playback failed. Close it and try again.'));}},[camera]);
 const fit=async image=>{setBusy(true);setError('');try{const result=await fitSelfie(drawSelfie(image));if(alive.current){setConfig(c=>({...c,...result,appearance_version:3}));stop();}}catch(e){if(alive.current)setError(e.message);}finally{if(alive.current)setBusy(false);}};
 const upload=async e=>{const photo=e.target.files?.[0];e.target.value='';if(!photo)return;if(!/^image\/(jpeg|png|webp)$/.test(photo.type)||photo.size>15*1024*1024){setError('Use a JPG, PNG or WebP smaller than 15 MB.');return;}const url=URL.createObjectURL(photo),img=new Image();try{img.src=url;await img.decode();await fit(img);}catch(e){if(alive.current)setError(e.message);}finally{URL.revokeObjectURL(url);}};
 return <section className="genesis-fields"><h2>Fit your face.</h2><p className="genesis-description">Use one clear, front-facing photo. Fit face proportions, complexion and the existing hair, then refine your look with sliders.</p><p className="genesis-note">The photo stays on this device; only appearance settings are saved. A photo estimates likeness, without depth scanning or creating a new hairstyle.</p>
 <div className="flex flex-wrap gap-3 my-4"><button type="button" className="genesis-secondary" disabled={busy||camera} onClick={start}>Enable camera</button><button type="button" className="genesis-secondary" disabled={busy} onClick={()=>file.current.click()}>Upload photo</button><input ref={file} className="hidden" type="file" aria-label="Upload face photo" accept="image/jpeg,image/png,image/webp" onChange={upload}/></div>
 {camera&&<div><video ref={video} autoPlay muted playsInline onLoadedData={()=>setReady(true)} className="w-full max-h-72 rounded-xl"/><button type="button" disabled={busy||!ready} onClick={()=>fit(video.current)} className="genesis-primary">Use this photo</button><button type="button" disabled={busy} onClick={stop} className="genesis-secondary">Close camera</button></div>}
 {busy&&<p role="status">Fitting your face… The first use downloads face models.</p>}{error&&<p role="alert" className="genesis-error">{error}</p>}{config.face_fit_source==='selfie'&&<p role="status">Face fitted. Review and refine your 3D preview.</p>}</section>;
}